### ISSUE TITLE
Deletion of receiver exports resulting in error

### ISSUE THREAD

**Issue by jkburges** [aodn/aatams#106]
Deletion of detection exports, and their associated detections, fails - or at least appear to the user to have failed.

**Steps to repeat**
1. Sign in and navigate to the "Receiver Exports" screen.
2. Select "info" symbol for the particular export (currently trying to find out which exports this affects).
3. Click "Delete".

**What should happen**
The export should be deleted, along with all of its associated detections, with a notification to that effect shown to the user.

**What does happen**
<blockquote>
Proxy Error

The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request POST /aatams/receiverDownloadFile/index.

Reason: Error reading from remote server

Apache Server at aatams.emii.org.au Port 443
 
</blockquote>

My guess is that the delete operation is taking a long time, upsetting apache which sits in between as a result.

**Comment by anguss00** [comment]
I will take this ring to Mordor
