### ISSUE TITLE
'species' table missing taxonomic information for some tagged animals

### ISSUE THREAD

**Issue by xhoenner** [aodn/aatams#122]
Some animals that have been tagged don't have a scientific_name, family, genus, or common_name linked to them. The column 'name' in the species has some information for some animals, but for some others it is null or incorrect (e.g. 'range test tag 200m, 37018036, example, example1)

Steps to reproduce:
  SELECT a.id, 
    a.version, 
    a.sex_id,
    a.species_id,
    s.*
  FROM animal a
  JOIN species s ON a.species_id = s.id
 WHERE s.common_name IS NULL OR s.scientific_name IS NULL OR family IS NULL;

What happens:
65 records are returned, for which there are no taxonomic information available (e.g. scientific_name, common_name, family, genus)

What should happen:
The species table should hold that information at least for all animals that have been tagged.

**Comment by xhoenner** [comment]
> I've been unable to reproduce this. I have add logging which should help us to see when and why this happens.

@jkburges not sure what you mean here, running the following query still returns 66 records.

SELECT * FROM species
WHERE spcode IS NULL

**Comment by dnahodil** [comment]
@jkburges was talking about trying to find the source of the bad data. He wasn't able to reproduce the bug that we think is causing these data errors.

**Comment by xhoenner** [comment]
@dnahodil @jkburges what's the way forward then?

**Comment by dnahodil** [comment]
@xhoenner we could go and look at the logs and see if the information that @jkburges added will give us any insight into where it is occurring. His logging might help us work out where the problem is or, if there is no information in the logs, it might mean that the problem doesn't occur anymore.

We can run a database update to clean up the bad data but if the problem is still occurring then we will still need to fix it.

I believe all AATAMS bugs are being reviewed at the moment and so we should get an idea out priorities and our plans for this when that has happened.

**Comment by xhoenner** [comment]
> @xhoenner we could go and look at the logs and see if the information that @jkburges added will give us any insight into where it is occurring. His logging might help us work out where the problem is or, if there is no information in the logs, it might mean that the problem doesn't occur anymore. We can run a database update to clean up the bad data but if the problem is still occurring then we will still need to fix it.

Makes perfect sense Dave, thanks for clearing things out!

> I believe all AATAMS bugs are being reviewed at the moment and so we should get an idea out priorities and our plans for this when that has happened.

Yes I believe they have reviewed the AATAMS bugs. This one though wouldn't be a high priority and therefore is unlikely to be addressed in the next little while. Could we get rid of these duplicates for now to have a clean slate and monitor if they reappear in the future?

**Comment by dnahodil** [comment]
I don't reckon we will be able to do that unless it gets a priority bump sorry, @xhoenner. If we are going to modify production data we'd be writing migration scripts so we can review them, test them somewhere, and only then run them on the production data. So it wouldn't be just a quick bit of SQL ninja skills.

If this bad data is causing you problems for your work (and I can understand that it would) you'd have to get @smancini to bring it up with @pblain at JPSR.

**Comment by astecken** [comment]
Related to this issue is the following and Xavier asked me to post it here:

RE: Null in AATAMS_acousticTagging_summary_species report; Tim wrote:
'Most of these (87%) are from the 2009 Bondi range experiment so I suspect they aren’t really valid species detections. Perhaps something to check with Andre. Another 10% are from Townsville reefs and probably should be showing up with the correct species ID. The rest is in the noise.'
 
Xavier responded:
'Following up from your comment this morning, I investigated the reason behind the ‘nulls’ in the AATAMS species report.
This issue is due to fields in a database table used for reporting that has missing values, it’s not due to people not entering metadata. In the meantime, see attached the corresponding list of species that I extracted from other fields of that same database table. You’ll notice that some have incomplete or erroneous information, that’s how it is currently in the database.
 
My response:
'The reason why there is metadata missing (at least in the case of the AATAMS Bondi Range Experiment 2009) is that these tags were range test tags for this particular experiment. As there is no option in the DB to indicate this, there will be missing metadata or ‘null species’ issues. We should maybe add an option under ‘species’ for ‘range test tag’ and ‘sentinel tag’. Then researchers can choose ‘sex’ as ‘unknown’. 
The ‘noise’ Tim mentioned would also partly be range test tags etc., I would think.'

**Comment by xhoenner** [comment]
This bug is still current.

> We should maybe add an option under ‘species’ for ‘range test tag’ and ‘sentinel tag’. Then researchers can choose ‘sex’ as ‘unknown’.

:+1: that's a great idea, instead of sex as 'unknown' it'd be best to have something like 'not applicable' for ‘range test tag’ and ‘sentinel tag’.

**Comment by xhoenner** [comment]
@dnahodil would you mind double checking that this issue is not similar to https://github.com/aodn/aatams/issues/123?

**Comment by dnahodil** [comment]
There is a similar problem with the species (where you can create them in a way you shouldn't be able to) but it's much less likely to be the cause of this data.

**Comment by xhoenner** [comment]
As it turns out, all of the 107 rows returned by the above query are also returned by the following query
```sql
SELECT id, version, name, common_name, scientific_name
  FROM species WHERE version = 0
  ORDER BY name DESC;
```

Not sure what's the purpose of the version field but it seems like people have been able to enter things manually into the `species` table as suggested by the content of the name field in the list below (*e.g.* 'sentinel tag', 'example 1' twice, 'control tag' 9 times). 

id | version | name | common_name | scientific_name
------------ | ------------- | ------------- | ------------- | ------------- | 
43109927 | 0 |  |  | 
117076209 | 0 |  |  | 
2854060 | 0 |  |  | 
4463119 | 0 |  |  | 
93015984 | 0 |  |  | 
126909560 | 0 |  |  | 
128839677 | 0 | sentinel tag |  | 
60747420 | 0 | sandbar |  | 
93588923 | 0 | range test tag 800m |  | 
93563417 | 0 | range test tag 700m |  | 
93556411 | 0 | range test tag 650m |  | 
93548905 | 0 | range test tag 600m |  | 
93529899 | 0 | range test tag 550m |  | 
93521393 | 0 | range test tag 500m |  | 
93513387 | 0 | range test tag 450m |  | 
93367381 | 0 | range test tag 400m |  | 
93354375 | 0 | range test tag 350m |  | 
93341869 | 0 | range test tag 300m |  | 
93327863 | 0 | range test tag 200m |  | 
3566950 | 0 | grey reef |  | 
3223978 | 0 | example1 |  | 
3223973 | 0 | example1 |  | 
3167080 | 0 | example |  | 
128164404 | 0 | control tag |  | 
128164414 | 0 | control tag |  | 
128164409 | 0 | control tag |  | 
128164385 | 0 | control tag |  | 
128164375 | 0 | control tag |  | 
128164394 | 0 | control tag |  | 
128164380 | 0 | control tag |  | 
128164370 | 0 | control tag |  | 
128164399 | 0 | control tag |  | 
77523685 | 0 | Trygonorrhina fasciata |  | 
77523705 | 0 | Trygonorrhina fasciata |  | 
77523695 | 0 | Trygonorrhina fasciata |  | 
107898783 | 0 | Stegostoma fasciatum |  | 
51060924 | 0 | Slit Eye Shark |  | 
51060932 | 0 | Slit Eye Shark |  | 
109421975 | 0 | Platycephalus caeruleopunctatus  |  | 
110411667 | 0 | Platycephalus caeruleopunctatus |  | 
85112396 | 0 | Maccullochella peelii mariensis |  | 
85112404 | 0 | Maccullochella peelii mariensis |  | 
85112417 | 0 | Maccullochella peelii mariensis |  | 
85112442 | 0 | Maccullochella peelii mariensis |  | 
85112423 | 0 | Maccullochella peelii mariensis |  | 
78228859 | 0 | Heterodontus portusjacksoni |  | 
78228848 | 0 | Heterodontus portusjacksoni |  | 
51061034 | 0 | Grey Reef Shark |  | 
11248103 | 0 | Coris aygula |  | 
128298610 | 0 | Carcharhinus obscurus |  | 
128298522 | 0 | Carcharhinus obscurus |  | 
128298558 | 0 | Carcharhinus obscurus |  | 
4479671 | 0 | Carcharhinus melanopterus |  | 
43649976 | 0 | Carcharhinus limbatus |  | 
43670006 | 0 | Carcharhinus leucas |  | 
128298650 | 0 | Carcharhinus brachyurus |  | 
128298390 | 0 | Carcharhinus brachyurus |  | 
128298398 | 0 | Carcharhinus brachyurus |  | 
128298406 | 0 | Carcharhinus brachyurus |  | 
128298414 | 0 | Carcharhinus brachyurus |  | 
128298422 | 0 | Carcharhinus brachyurus |  | 
128298430 | 0 | Carcharhinus brachyurus |  | 
128298438 | 0 | Carcharhinus brachyurus |  | 
128298446 | 0 | Carcharhinus brachyurus |  | 
128298454 | 0 | Carcharhinus brachyurus |  | 
128298462 | 0 | Carcharhinus brachyurus |  | 
128298472 | 0 | Carcharhinus brachyurus |  | 
128298480 | 0 | Carcharhinus brachyurus |  | 
128298490 | 0 | Carcharhinus brachyurus |  | 
128298500 | 0 | Carcharhinus brachyurus |  | 
128298512 | 0 | Carcharhinus brachyurus |  | 
128298534 | 0 | Carcharhinus brachyurus |  | 
128298542 | 0 | Carcharhinus brachyurus |  | 
128298550 | 0 | Carcharhinus brachyurus |  | 
128298572 | 0 | Carcharhinus brachyurus |  | 
128298580 | 0 | Carcharhinus brachyurus |  | 
128298588 | 0 | Carcharhinus brachyurus |  | 
128298598 | 0 | Carcharhinus brachyurus |  | 
128298618 | 0 | Carcharhinus brachyurus |  | 
128298632 | 0 | Carcharhinus brachyurus |  | 
128298640 | 0 | Carcharhinus brachyurus |  | 
128298380 | 0 | Carcharhinus brachyurus |  | 
43669807 | 0 | Carcharhinus amblyrhynchos |  | 
4479636 | 0 | Aprion virscens |  | 
2854019 | 0 | 37353001 - Pagrus auratus (Snapper) |  | 
56773095 | 0 | 37018036 |  | 
62120583 | 0 | 37014001 - Rhincodon typus (Whale Shark) |  | 
60491400 | 0 | 37010003 - Carcharodon carcharias (White Shark) |  | 
60491394 | 0 | 37010003 - Carcharodon carcharias (White Shark) |  | 
60491388 | 0 | 37010003 - Carcharodon carcharias (White Shark) |  | 
60491382 | 0 | 37010003 - Carcharodon carcharias (White Shark) |  | 
60491376 | 0 | 37010003 - Carcharodon carcharias (White Shark) |  | 
60491370 | 0 | 37010003 - Carcharodon carcharias (White Shark) |  | 
60491364 | 0 | 37010003 - Carcharodon carcharias (White Shark) |  | 
60491358 | 0 | 37010003 - Carcharodon carcharias (White Shark) |  | 
60491346 | 0 | 37010003 - Carcharodon carcharias (White Shark) |  | 
60491316 | 0 | 37010003 - Carcharodon carcharias (White Shark) |  | 
60491310 | 0 | 37010003 - Carcharodon carcharias (White Shark) |  | 
60491340 | 0 | 37010003 - Carcharodon carcharias (White Shark) |  | 
60491334 | 0 | 37010003 - Carcharodon carcharias (White Shark) |  | 
60491328 | 0 | 37010003 - Carcharodon carcharias (White Shark) |  | 
60491322 | 0 | 37010003 - Carcharodon carcharias (White Shark) |  | 
60491352 | 0 | 37010003 - Carcharodon carcharias (White Shark) |  | 
60491424 | 0 | 37010003 - Carcharodon carcharias (White Shark) |  | 
60491418 | 0 | 37010003 - Carcharodon carcharias (White Shark) |  | 
60491412 | 0 | 37010003 - Carcharodon carcharias (White Shark) |  | 
60491406 | 0 | 37010003 - Carcharodon carcharias (White Shark) |  |

**Comment by jkburges** [comment]
> Not sure what's the purpose of the version field

It's used by hibernate (the "object relational mapping" framework), and is incremented each time a row is updated.  It's nothing special for AATAMS.

**Comment by xhoenner** [comment]
I changed the label on this one from low to high priority as it has come to my attention that this issue impacts the content of CSV files users get to download via the [Tag Detections page] (https://aatams.emii.org.au/aatams/detection/list).

The ~100 species listed above have been manually entered by people due to the absence of constraints in the (Tag Release page) [https://aatams.emii.org.au/aatams/animalRelease/list]. These `species` entries don’t comply with the CAAB format that is meant to be used by the web app, therefore a lot of fields in the `species` table that should be compulsory are left blank. These manual, incomplete species entries subsequently impact users willing to download tag detections as the species field in the CSV gets populated from the following combination of fields: ${spcode} - ${scientificName} (${commonName}), see the corresponding [Groovy file] (https://github.com/aodn/aatams/blob/master/src/groovy/au/org/emii/aatams/detection/DetectionView.groovy).

 So in my opinion the following steps need to be taken in the following order:
  1. Find out all the releases that have been linked to a species in the above list and fix these up by assigning them to an existing CAAB-registered species.
  2. Once 1 is done, clean up the `species` table by removing all the entries listed above.
  3. Add constraints to the Tag Release page so that users have to use the existing, cleaned-up, drop down menu listing all CAAB-registered species.

Obviously these steps will require quite some work, so an alternative, quick-fix, option for now would be to amend the Groovy file mentioned above by editing the ``getSpeciesName`` function to read: if (!spcode) {return "${name}"}.

@julian1 how much work would it require to implement step 3?

**Comment by xhoenner** [comment]
114 tags have invalid species name, *i.e.* typed in or pasted by users instead of using the drop-down CAAB code list, see below @fjaine. 

The first 13 tags have been re-assigned as being range test tags so I will delete the corresponding release for these. I suspect the next eight tags (AATAMS Cabbage Tree project) are also range test tags as species_name = 'control tag' but it'd be worth double checking that with the PIs. For the others I'd suggest changing the species name manually through the web app when the correct species name is obvious, otherwise contact the PIs.

transmitter_id | tag_id | release_id | transmitter_type | project_name | species_name
-------------- | ------ | ---------- | ---------------- | ------------ | ------------
A69-9001-1143 | 93015978 | 93015986 | RANGE TEST | AATAMS Bondi line | 
A69-1303-14657 | 93016144 | 128164416 | RANGE TEST | AATAMS Bondi range experiment 2009 | control tag
A69-1303-54479 | 93016088 | 93563419 | RANGE TEST | AATAMS Bondi range experiment 2009 | range test tag 700m
A69-1303-54480 | 93016092 | 93588925 | RANGE TEST | AATAMS Bondi range experiment 2009 | range test tag 800m
A69-1303-54481 | 93016096 | 93556413 | RANGE TEST | AATAMS Bondi range experiment 2009 | range test tag 650m
A69-1303-54482 | 93016100 | 93521395 | RANGE TEST | AATAMS Bondi range experiment 2009 | range test tag 500m
A69-1303-54483 | 93016104 | 93341871 | RANGE TEST | AATAMS Bondi range experiment 2009 | range test tag 300m
A69-1303-54485 | 93016112 | 93513389 | RANGE TEST | AATAMS Bondi range experiment 2009 | range test tag 450m
A69-1303-54486 | 93016116 | 93367383 | RANGE TEST | AATAMS Bondi range experiment 2009 | range test tag 400m
A69-1303-54487 | 93016120 | 93548907 | RANGE TEST | AATAMS Bondi range experiment 2009 | range test tag 600m
A69-1303-54488 | 93016124 | 93327865 | RANGE TEST | AATAMS Bondi range experiment 2009 | range test tag 200m
A69-1303-54489 | 93016128 | 93529901 | RANGE TEST | AATAMS Bondi range experiment 2009 | range test tag 550m
A69-1303-54490 | 93016132 | 93354377 | RANGE TEST | AATAMS Bondi range experiment 2009 | range test tag 350m
A69-9001-65066 | 128164314 | 128164377 | PINGER | AATAMS Cabbage Tree Bay Aquatic Reserve (CTBAR) | control tag
A69-9001-65067 | 128164318 | 128164372 | PINGER | AATAMS Cabbage Tree Bay Aquatic Reserve (CTBAR) | control tag
A69-9001-65068 | 128164322 | 128164396 | PINGER | AATAMS Cabbage Tree Bay Aquatic Reserve (CTBAR) | control tag
A69-9001-65069 | 128164389 | 128164387 | PINGER | AATAMS Cabbage Tree Bay Aquatic Reserve (CTBAR) | control tag
A69-9001-65070 | 128164330 | 128164382 | PINGER | AATAMS Cabbage Tree Bay Aquatic Reserve (CTBAR) | control tag
A69-9001-65071 | 128164334 | 128164406 | PINGER | AATAMS Cabbage Tree Bay Aquatic Reserve (CTBAR) | control tag
A69-9001-65072 | 128164338 | 128164401 | PINGER | AATAMS Cabbage Tree Bay Aquatic Reserve (CTBAR) | control tag
A69-9001-65073 | 128164342 | 128164411 | PINGER | AATAMS Cabbage Tree Bay Aquatic Reserve (CTBAR) | control tag
A69-9002-14805 | 56771128 | 56773097 | PRESSURE | AATAMS Heron Island | 37018036
A69-1303-53221 | 11248099 | 11248105 | PINGER | AATAMS Ningaloo Reef Ecosystem Tracking Array (NRETA) | Coris aygula
A69-9001-28009 | 129386039 | 129386045 | PINGER | AATAMS Ningaloo Reef Ecosystem Tracking Array (NRETA) | TRIENODON OBESUS
A69-1601-25834 | 110521053 | 128841628 | PINGER | Chondrichthyan monitoring of south-east Australia | Schoola shark
A69-1601-4065 | 110520089 | 129386541 | PINGER | Chondrichthyan monitoring of south-east Australia | Smooth sting
A69-9002-8208 | 111101773 | 128840914 | ACCELEROMETER | Chondrichthyan monitoring of south-east Australia | Broadnose
A69-9001-28409 | 56771062 | 62120585 | PINGER | Ecocean Ningaloo whale shark project | 37014001 - Rhincodon typus (Whale Shark)
A69-9001-30967 | 129583829 | 129588646 | PINGER | FRDC WA commercial sharks | 37018007 - Carcharhinus plumbeus (Sandbar Shark)
A69-9001-31040 | 129584057 | 129636345 | PINGER | FRDC WA commercial sharks | sandbar shark
A69-1303-27173 | 60481158 | 60491402 | PINGER | FSRF Acoustic network | 37010003 - Carcharodon carcharias (White Shark)
A69-1303-27174 | 60481162 | 60491408 | PINGER | FSRF Acoustic network | 37010003 - Carcharodon carcharias (White Shark)
A69-1303-27175 | 60481166 | 60491420 | PINGER | FSRF Acoustic network | 37010003 - Carcharodon carcharias (White Shark)
A69-1303-27176 | 60481170 | 60491414 | PINGER | FSRF Acoustic network | 37010003 - Carcharodon carcharias (White Shark)
A69-1303-27177 | 60481174 | 60491426 | PINGER | FSRF Acoustic network | 37010003 - Carcharodon carcharias (White Shark)
A69-1303-28761 | 60481202 | 60491372 | PINGER | FSRF Acoustic network | 37010003 - Carcharodon carcharias (White Shark)
A69-1303-28762 | 60481206 | 60491366 | PINGER | FSRF Acoustic network | 37010003 - Carcharodon carcharias (White Shark)
A69-1303-28763 | 60481210 | 60491360 | PINGER | FSRF Acoustic network | 37010003 - Carcharodon carcharias (White Shark)
A69-1303-28764 | 60481214 | 60491354 | PINGER | FSRF Acoustic network | 37010003 - Carcharodon carcharias (White Shark)
A69-1303-28765 | 60481218 | 60491348 | PINGER | FSRF Acoustic network | 37010003 - Carcharodon carcharias (White Shark)
A69-1303-28766 | 60481222 | 60491342 | PINGER | FSRF Acoustic network | 37010003 - Carcharodon carcharias (White Shark)
A69-1303-29113 | 60481138 | 60491336 | PINGER | FSRF Acoustic network | 37010003 - Carcharodon carcharias (White Shark)
A69-1303-29114 | 60481134 | 60491312 | PINGER | FSRF Acoustic network | 37010003 - Carcharodon carcharias (White Shark)
A69-1303-29115 | 60481130 | 60491330 | PINGER | FSRF Acoustic network | 37010003 - Carcharodon carcharias (White Shark)
A69-1303-29116 | 60481126 | 60491324 | PINGER | FSRF Acoustic network | 37010003 - Carcharodon carcharias (White Shark)
A69-1303-29976 | 60481178 | 60491396 | PINGER | FSRF Acoustic network | 37010003 - Carcharodon carcharias (White Shark)
A69-1303-29977 | 60481182 | 60491390 | PINGER | FSRF Acoustic network | 37010003 - Carcharodon carcharias (White Shark)
A69-1303-29978 | 60481194 | 60491384 | PINGER | FSRF Acoustic network | 37010003 - Carcharodon carcharias (White Shark)
A69-1303-29979 | 60481198 | 60491378 | PINGER | FSRF Acoustic network | 37010003 - Carcharodon carcharias (White Shark)
A69-1303-29980 | 60481186 | 60491318 | PINGER | FSRF Acoustic network | 37010003 - Carcharodon carcharias (White Shark)
A69-1303-33179 | 128227371 | 128298382 | PINGER | Gulf St Vincent monitoring | Carcharhinus brachyurus
A69-1303-33180 | 128262295 | 128298392 | PINGER | Gulf St Vincent monitoring | Carcharhinus brachyurus
A69-1303-33182 | 128297259 | 128298400 | PINGER | Gulf St Vincent monitoring | Carcharhinus brachyurus
A69-1303-33183 | 128297265 | 128298408 | PINGER | Gulf St Vincent monitoring | Carcharhinus brachyurus
A69-1303-33184 | 128297269 | 128298416 | PINGER | Gulf St Vincent monitoring | Carcharhinus brachyurus
A69-1303-33187 | 128297275 | 128298424 | PINGER | Gulf St Vincent monitoring | Carcharhinus brachyurus
A69-1303-33188 | 128297279 | 128298432 | PINGER | Gulf St Vincent monitoring | Carcharhinus brachyurus
A69-1303-33189 | 128297285 | 128298440 | PINGER | Gulf St Vincent monitoring | Carcharhinus brachyurus
A69-1303-33190 | 128297289 | 128298448 | PINGER | Gulf St Vincent monitoring | Carcharhinus brachyurus
A69-1303-33191 | 128297293 | 128298456 | PINGER | Gulf St Vincent monitoring | Carcharhinus brachyurus
A69-1303-33192 | 128297297 | 128298464 | PINGER | Gulf St Vincent monitoring | Carcharhinus brachyurus
A69-1303-33193 | 128297303 | 128298474 | PINGER | Gulf St Vincent monitoring | Carcharhinus brachyurus
A69-1303-33194 | 128297307 | 128298482 | PINGER | Gulf St Vincent monitoring | Carcharhinus brachyurus
A69-1303-33195 | 128297313 | 128298492 | PINGER | Gulf St Vincent monitoring | Carcharhinus brachyurus
A69-1303-33196 | 128297317 | 128298502 | PINGER | Gulf St Vincent monitoring | Carcharhinus brachyurus
A69-1303-33197 | 128297321 | 128298514 | PINGER | Gulf St Vincent monitoring | Carcharhinus brachyurus
A69-1303-49136 | 757290 | 128298524 | PINGER | Gulf St Vincent monitoring | Carcharhinus obscurus
A69-1303-52472 | 128297333 | 128298536 | PINGER | Gulf St Vincent monitoring | Carcharhinus brachyurus
A69-1303-52639 | 3084739 | 128298544 | PINGER | Gulf St Vincent monitoring | Carcharhinus brachyurus
A69-1303-52640 | 3084745 | 128298552 | PINGER | Gulf St Vincent monitoring | Carcharhinus brachyurus
A69-1303-52644 | 3084751 | 128298560 | PINGER | Gulf St Vincent monitoring | Carcharhinus obscurus
A69-1303-52645 | 3084753 | 128298574 | PINGER | Gulf St Vincent monitoring | Carcharhinus brachyurus
A69-1303-52646 | 3084755 | 128298582 | PINGER | Gulf St Vincent monitoring | Carcharhinus brachyurus
A69-1303-52647 | 3084757 | 128298590 | PINGER | Gulf St Vincent monitoring | Carcharhinus brachyurus
A69-1303-52648 | 3084759 | 128298600 | PINGER | Gulf St Vincent monitoring | Carcharhinus brachyurus
A69-1303-52649 | 3084761 | 128298612 | PINGER | Gulf St Vincent monitoring | Carcharhinus obscurus
A69-1303-52650 | 3084763 | 128298620 | PINGER | Gulf St Vincent monitoring | Carcharhinus brachyurus
A69-1303-52651 | 3084765 | 128298634 | PINGER | Gulf St Vincent monitoring | Carcharhinus brachyurus
A69-1303-52652 | 3084767 | 128298642 | PINGER | Gulf St Vincent monitoring | Carcharhinus brachyurus
A69-1303-52653 | 3084769 | 128298652 | PINGER | Gulf St Vincent monitoring | Carcharhinus brachyurus
A69-1303-47002 | 43649980 | 43649978 | PINGER | JCU Cleveland Bay | Carcharhinus limbatus
A69-1601-36745 | 129187094 | 129187140 | PINGER | Lane Cove River Australian Bass | Macquaria novemaculeata
A69-1601-36747 | 129187098 | 129187148 | PINGER | Lane Cove River Australian Bass | 
A69-1601-11759 | 110411663 | 110411669 | PINGER | NSW DPI (Artificial Reef Network) | Platycephalus caeruleopunctatus
A69-1601-11760 | 109421971 | 109421977 | PINGER | NSW DPI (Artificial Reef Network) | Platycephalus caeruleopunctatus 
A69-1303-51409 | 107799968 | 129661772 | PINGER | NSW DPI Coastal and Estuarine Fish Tracking (CEFT) | 37296004 - Platycephalus fuscus (Dusky Flathead)
A69-1303-64253 | 108925524 | 129662065 | PINGER | NSW DPI Coastal and Estuarine Fish Tracking (CEFT) | Mulloway
A69-1601-31618 | 4462962 | 4463121 | PINGER | NSW DPI Coastal and Estuarine Fish Tracking (CEFT) | 
A69-1601-32748 | 129579933 | 129581427 | PINGER | NSW DPI Coastal and Estuarine Fish Tracking (CEFT) | Sand Whiting
A69-1601-31482 | 130193908 | 130193906 | PINGER | Sevengill Shark tracking in Victoria | Braodnose sevengill shark
A69-1601-31488 | 130193967 | 130193965 | PINGER | Sevengill Shark tracking in Victoria | 37005002 - Notorynchus cepedianus (Broadnose Shark)
A69-1601-31490 | 130193993 | 130193991 | PINGER | Sevengill Shark tracking in Victoria | 37005002 - Notorynchus cepedianus (Broadnose Shark)
A69-1601-31491 | 130194004 | 130194002 | PINGER | Sevengill Shark tracking in Victoria | 37005002 - Notorynchus cepedianus (Broadnose Shark)
A69-1601-31492 | 130194015 | 130194013 | PINGER | Sevengill Shark tracking in Victoria | 37005002 - Notorynchus cepedianus (Broadnose Shark)
A69-1601-31494 | 130194026 | 130194024 | PINGER | Sevengill Shark tracking in Victoria | 37005002 - Notorynchus cepedianus (Broadnose Shark)
A69-1601-31495 | 130194037 | 130194035 | PINGER | Sevengill Shark tracking in Victoria | 37005002 - Notorynchus cepedianus (Broadnose Shark)
A69-1601-31496 | 130194048 | 130194046 | PINGER | Sevengill Shark tracking in Victoria | 37005002 - Notorynchus cepedianus (Broadnose Shark)
A69-1601-31498 | 130194134 | 130194132 | PINGER | Sevengill Shark tracking in Victoria | 37005002 - Notorynchus cepedianus (Broadnose Shark)
A69-1601-31499 | 130194079 | 130194077 | PINGER | Sevengill Shark tracking in Victoria | 37005002 - Notorynchus cepedianus (Broadnose Shark)
A69-1601-31500 | 130194090 | 130194088 | PINGER | Sevengill Shark tracking in Victoria | 37005002 - Notorynchus cepedianus (Broadnose Shark)
A69-1601-31502 | 130194155 | 130194153 | PINGER | Sevengill Shark tracking in Victoria | 37005002 - Notorynchus cepedianus (Broadnose Shark)
A69-1601-31503 | 130194166 | 130194164 | PINGER | Sevengill Shark tracking in Victoria | 37005002 - Notorynchus cepedianus (Broadnose Shark)
A69-1601-31504 | 130194101 | 130194099 | PINGER | Sevengill Shark tracking in Victoria | 37005002 - Notorynchus cepedianus (Broadnose Shark)
A69-1601-31505 | 130194177 | 130194175 | PINGER | Sevengill Shark tracking in Victoria | 37005002 - Notorynchus cepedianus (Broadnose Shark)
A69-1601-31506 | 130194188 | 130194186 | PINGER | Sevengill Shark tracking in Victoria | 37005002 - Notorynchus cepedianus (Broadnose Shark)
A69-1601-31507 | 130194199 | 130194197 | PINGER | Sevengill Shark tracking in Victoria | 37005002 - Notorynchus cepedianus (Broadnose Shark)
A69-1601-31508 | 130194210 | 130194208 | PINGER | Sevengill Shark tracking in Victoria | 37005002 - Notorynchus cepedianus (Broadnose Shark)
A69-1601-31509 | 130194112 | 130194110 | PINGER | Sevengill Shark tracking in Victoria | 37005002 - Notorynchus cepedianus (Broadnose Shark)
A69-1601-31510 | 130194123 | 130194121 | PINGER | Sevengill Shark tracking in Victoria | 37005002 - Notorynchus cepedianus (Broadnose Shark)
A69-9002-14747 | 43669446 | 43669809 | PRESSURE | Townsville Reefs | Carcharhinus amblyrhynchos
A69-9002-14770 | 43669552 | 43670008 | PRESSURE | Townsville Reefs | Carcharhinus leucas
A69-9002-14778 | 43669584 | 51061036 | PRESSURE | Townsville Reefs | Grey Reef Shark
A69-9002-14786 | 43669616 | 51060934 | PRESSURE | Townsville Reefs | Slit Eye Shark
A69-9002-14787 | 43669620 | 51060926 | PRESSURE | Townsville Reefs | Slit Eye Shark

**Comment by xhoenner** [comment]
@fjaine all good now, the above query doesn't return any row!

@julian1 how much work would it require to add constraints to the Tag Release page so that users have to use the existing, cleaned-up, drop down menu listing all CAAB-registered species? If we don't fix that up the same issue will come up again.

**Comment by fjaine** [comment]
Nice one @xhoenner!

Agreed - Having species entry as a drop down menu of all available options will help prevent further erroneous entries by users

**Comment by julian1** [comment]
hey @xhoenner, does it just involve cleaning up the html to disable/remove links? I'm sure that can be done quickly - but would probably need to be prioritized by jpsr. Are you able to look at the template grails code yourself to perhaps identify what's needed?

**Comment by xhoenner** [comment]
Species have been manually entered by people due to the absence of constraints in the [Tag Release page] (https://animaltracking.aodn.org.au/animalRelease/create), *i.e.* there's no drop down menu while there is for the project and sex fields. The corresponding code seems to sit in grails-app/views/animalRelease/create.gsp but I'm not sure whether modifying the species part of the code (see below) to mimic the project or sex part is the right way to go here. Does that sound like a sensible approach to you @julian1?

*Species*
 ```gsp
                            <tr class="prop">
                                <td valign="top" class="name">
                                    <label class="compulsory" for="species"><g:message code="animalRelease.animal.species.label" default="Species" /></label>
                                </td>
                                <td valign="top" class="value ${hasErrors(bean: animalReleaseInstance.animal, field: 'species', 'errors')}">
                                  <g:hiddenField name="speciesId" value="${species?.id}"/>
                                  <g:textField name="speciesName" value="${species?.name}" />
                                </td>
                            </tr>

```

*Sex*
```gsp
                            <tr class="prop">
                                <td valign="top" class="name">
                                    <label class="compulsory" for="sex"><g:message code="animalRelease.animal.sex.label" default="Sex" /></label>
                                </td>
                                <td valign="top" class="value ${hasErrors(bean: animalReleaseInstance.animal, field: 'sex', 'errors')}">
                                    <g:select name="sex.id" 
                                              from="${au.org.emii.aatams.Sex.list()}" 
                                              optionKey="id" value="${animalReleaseInstance?.animal?.sex?.id}" 
                                              noSelection="['':'Not specified']"/>
                                </td>
                            </tr>
```

**Comment by xhoenner** [comment]
okay I've implemented that change on the dev-instance, which makes the web-app extremely slow as it must then retrieve the complete list of ~50,000 species in that drop-down menu. Any suggestion @julian1?

**Comment by xhoenner** [comment]
@julian1 as discussed I modified the Animal.groovy file by adding the belongsTo constraint below but am now getting the following 500 error.

```groovy
package au.org.emii.aatams

class Animal implements Embargoable {
    static hasMany = [releases: AnimalRelease]
    Species species
    Sex sex

    static constraints = {
        sex(nullable:true)
    }

    static belongsTo = [species: Species, animal: Animal]
    static transients = ['embargoed', 'project']
```

![screen shot 2016-10-13 at 1 48 24 pm](https://cloud.githubusercontent.com/assets/3443821/19335021/cb7af068-914b-11e6-9c5b-46cb94a8b9cb.jpg)

**Comment by julian1** [comment]
Animal only has a reference to species,
```
      Table "aatams.animal"
   Column   |  Type  | Modifiers 
------------+--------+-----------
 id         | bigint | not null
 version    | bigint | not null
 sex_id     | bigint | 
 species_id | bigint | not null
Indexes:
    "animal_pkey" PRIMARY KEY, btree (id)
Foreign-key constraints:
    "fkabc58dfc94348341" FOREIGN KEY (species_id) REFERENCES aatams.species(id)
```
So try with just the species, eg,

```
  static belongsTo = [species: Species ]
```

**Comment by xhoenner** [comment]
thanks, tried that but it didn't change the current behaviour of the web app in any way.

**Comment by julian1** [comment]
You can try putting in the reverse relationship eg. hasMany in class Species, pointing back at Animal. Otherwise, raise it with jpsr.

**Comment by xhoenner** [comment]
Tried that too @julian1, thanks for the suggestion, however, it looks like it's going to be a JPSR matter...
