### ISSUE TITLE
Some animals listed in the 'animal' table are not listed in the 'animal_release' table

### ISSUE THREAD

**Issue by xhoenner** [aodn/aatams#123]
Steps to reproduce:
```  SELECT *
  FROM animal a
  FULL JOIN animal_release ar ON ar.animal_id = a.id
 	WHERE animal_id IS NULL
	ORDER BY a.id;```

What happens:
108 records from the 'animal' table are returned with no associated information from the 'animal_release' table. 

What should happen:
@jkburges says that this is 'possible if a release is created then deleted (the release "belongs" to the animal, not the other way around)'. Shouldn't the animal be deleted at the same time then?

**Comment by xhoenner** [comment]
Still current, 113 records are returned now instead of 108 when running the above query.

IMO this issue requires to: 
* Prevent users in the web app to create an animal record without an animal_release record.
* Clean up the existing 113 animal records that don't have a corresponding animal_release record.

**Comment by astecken** [comment]
@xhoenner could you send em a list with those 113 animal records incl. project so that I can contact owners? Then I could at least work on that part of this issue.

**Comment by xhoenner** [comment]
Unfortunately I can't do that @astecken since these animal ids are not found in the animal_release table, which holds project-related information.

**Comment by astecken** [comment]
@xhoenner What do you suggest instead? Can we identify at all who has entered this data so we can contact them?

**Comment by xhoenner** [comment]
No there's no way to link these erroneous metadata to any project. The clean up will therefore have to be done from our end. 

This issue is not critical but it is puzzling to see that people managed to enter animal information without any reference to the animal_release table as this is all done through https://aatams.emii.org.au/aatams/animalRelease/create. Any idea how this might have happen @dnahodil?

**Comment by dnahodil** [comment]
Okay, I've checked things out and I've found a way that animals can be created without a release. My suggestion is this:
* We remove this method of creating Animals
* We clear the erroneous records from the database
* We come back in 6 months and see if there are any new ones

To note: I had a theory that if you were entering an animal release but had an error in the form that an animal might be created by mistake (even though the animal release didn't save). I tried this out and it didn't seem to be the case - I couldn't create an animal this way. But, if after 6 months we see more bad animals, it might be worth checking again.

**Comment by dnahodil** [comment]
I've been thinking a bit and I think if this way I've just found of creating animals was being use/abused then I think we'd have more extra animals than we currently do. We still need to fix it, but my gut says that these erroneous animals are probably being created by the animal released page (maybe people going back and editing a release after it is already created?)

**Comment by xhoenner** [comment]
Still current, 468 records are returned now instead of 113 when running:

```sql
SELECT * FROM animal a 
FULL JOIN animal_release ar ON ar.animal_id = a.id 
WHERE animal_id IS NULL
ORDER BY a.id;
```

https://github.com/aodn/aatams/pull/322 will clean up these erroneous records but it looks like there is still a way for animals to be created without a corresponding release since the number of records mentioned above increased threefold since Nov. 24 2015.
