### ISSUE TITLE
Report on unknown tags

### ISSUE THREAD

**Issue by jkburges** [aodn/aatams#151]
Here's some adhoc SQL to report on the list of tag IDs appearing in the uploaded detections which are otherwise unknown to the DB:

```sql
select distinct transmitter_id from aatams.valid_detection
except
select distinct transmitter_id from aatams.sensor
order by transmitter_id
```

[The results of running the query are here...](https://gist.github.com/jkburges/1760c96abc96f5220c85)

Note: there are about ~5700 unknown tag IDs out of the ~8700 distinct tag IDs appearing in the DB.

**Comment by xhoenner** [comment]
Also available in the data reports
