### ISSUE TITLE
Refresh after clearing filter on Tag Detection List takes 1 minute in Systest

### ISSUE THREAD

**Issue by jonescc** [aodn/aatams#178]
To reproduce, add a filter wait until results are returned and then clear the filter and then wait for the results to be returned.

It takes around 1 minute for the unconstrained results to be returned

It should take as long as it took to display the unconstrained page when going to the tag detection list for the first time.

**Comment by dnahodil** [comment]
This seems like it might have been resolved by our recent changes, @jonescc. Would you mind confirming?

**Comment by jkburges** [comment]
My guess is that it's resolved because of the removal of counting...

**Comment by jonescc** [comment]
Yep resolved.
