### ISSUE TITLE
Error page when editing Project as project administrator

### ISSUE THREAD

**Issue by dnahodil** [aodn/aatams#179]
**Steps to reproduce**
Log in as a user with administrator and read/write access to a Project
View that Project from the list
Click the 'edit' button

**What should happen**
Taken to edit screen

**What does happen**
An error page is displayed

**Comment by anguss00** [comment]
I'm now on this

**Comment by jkburges** [comment]
With reference to https://github.com/aodn/aatams/blob/master/doc/AATAMS%20User%20Interface%20Specification%20(post%20data%20committee).pdf, I think that only PIs should be able to edit projects.  i.e. the edit button should only be visible to sys admins and PIs on a particular project.

If someone tries to go directly to the edit URL for a project they are not authorised to edit, it should redirect to the "not authorised to view this page" screen.
