### ISSUE TITLE
Failing integration tests

### ISSUE THREAD

**Issue by dnahodil** [aodn/aatams#197]
There is an integration test that fails on @dnahodil's dev machine and Jenkins, but is fine on @jkburges' machine and Travis. 

The problem test is `QueryServiceTests.testBetweenRestriction()`

<pre>
junit.framework.AssertionFailedError: junit.framework.AssertionFailedError: expected:<9> but was:<0>
	at au.org.emii.aatams.filter.QueryServiceTests.assertContainsAll(QueryServiceTests.groovy:416)
	at au.org.emii.aatams.filter.QueryServiceTests.this$7$assertContainsAll(QueryServiceTests.groovy)
	at au.org.emii.aatams.filter.QueryServiceTests$this$7$assertContainsAll.callCurrent(Unknown Source)
	at au.org.emii.aatams.filter.QueryServiceTests.assertQuery(QueryServiceTests.groovy:409)
	at au.org.emii.aatams.filter.QueryServiceTests.this$7$assertQuery(QueryServiceTests.groovy)
	at au.org.emii.aatams.filter.QueryServiceTests$this$7$assertQuery.callCurrent(Unknown Source)
	at au.org.emii.aatams.filter.QueryServiceTests.testBetweenRestriction(QueryServiceTests.groovy:121)
</pre>

**Comment by dnahodil** [comment]
**Some troubleshooting results**

The code:
<pre>def sql = new Sql(dataSource)
def dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss z")
def cal = Calendar.instance

println TimeZone.default.ID
println dateFormat.format(cal.time)
sql.eachRow('select now()') { row ->
    println row
}</pre>

Output from Jerkins/my machine (tests fail)
>Australia/Hobart
2015/02/06 12:38:53 AEDT
[now:2015-02-06 12:38:53.957375]

Output from Travis (test pass)
>Australia/Hobart
2015/02/06 12:44:30 EST
[now:2015-02-06 12:44:30.636561]

Note different timezones when printing date from Groovy. `AEDT` vs `EST`

**Comment by jkburges** [comment]
So, is that specifically why the test is failing, i.e. the different timezone abbreviation?

**Comment by dnahodil** [comment]
No, it's not to do with the abbreviation AFAIK.

**Comment by dnahodil** [comment]
Ok, @jkburges was right. The timezone wasn't failing the test -as in a string comparison or something- but it was causing a String -> Date parse to give different results.

The cause is that my machine has Java version 1.7.0_75 which comes with the [IANA timezone database](http://www.iana.org/time-zones) version 2014j while Travis has Java version 1.7.0_u65 which has version 2014c of the timezone database. In version 2014j all the Australian timezones have the 'A' included in their short versions. So EST -> AEST, EDT -> AEDT, WST -> AWST, and so on. Presumably this is to remove ambiguity (some people [argued about it](http://blog.gmane.org/gmane.comp.time.tz/month=20130401) on the internet, once). So this test would also have broken on Travis and Jon's machines when their JDKs were updated.
