### ISSUE TITLE
Recoveries not showing for certain deployments

### ISSUE THREAD

**Issue by jkburges** [aodn/aatams#202]
Some deployments are showing up as having no associated recovery, even though the recovery has been entered.

**Steps to reproduce**
1. Search for receiver "VR2W-101759" (this is but one example)
2. Click on "VR2W-101759 (Receiver)" at the top of the search results.

**What does happen**
Note there are two (as at 17/02/2015) deployments showing without associated recoveries.

**What should happen**
All deployments should have an associated recovery (for this receiver, at least).

The information seems to be in the DB correctly, this can be verified for example:

```sql
select serial_number, deploymentdatetime_timestamp, recoverydatetime_timestamp from device 
join receiver_deployment on device.id = receiver_deployment.receiver_id
join receiver_recovery on receiver_deployment.id = receiver_recovery.deployment_id
where serial_number = '101759' 
```

**Comment by jkburges** [comment]
I *think* what has happened here is that the user "Andrew Boomer" has been removed from a number of projects (i.e. certain "project_roles" have been deleted).  `Recoveries` belong to project_roles, and hence these have been deleted too.

We can probably recover what's been deleted from backups, but we need to have specified what's the correct behaviour for this use case (i.e. were someone is removed from a project, what happens to all the things which were owned by them).

**Comment by jkburges** [comment]
/cc @danfruehauf @pblain we have backups going back to 2015.01.23.05.19.59 from which we can probably recover the deleted info, but it would require a little bit of SQL hacking (not too much, hopefully).

I have "kept" the oldest backup at "jkburges@8-nec-hob:/var/backups/kept_backups".  Otherwise, I have the non-deleted stuff on my local machine, and it's also at 3-aws-syd.

**Comment by danfruehauf** [comment]
VIT?

**Comment by kereid** [comment]
Andrew Boomer was only deleted from the projects yesterday 16/02/15

**Comment by jkburges** [comment]
That's good.  I *think* that it should be fairly easy to recover/migrate
the data from backups - and IMO, it should be a VIT.  The question remains
though how to handle this use case properly.  I can't remember *why*
recoveries are owned by project_roles and not simply by users (in which
case, this problem wouldn't exist, as the user in this case has not been
removed).  I'll take a look at the code tomorrow and see if I can figure
that out.

**Comment by kereid** [comment]
From Andre: I was reviewing the member list yesterday and deleted some double entries and added new people. I came across Andrew Boomer and that he still has read/write access to several projects. 

Confirming that by double entries he meant he deleted those that were in the database twice under different usernames.

They were:

Ian Jonsen
Michael Lowry
Richard Pillans
Thomas Stieglitz

I also took Jessica Boomer of all of her projects that she was working on in the past; there might have been recoveries for her too.

**Comment by jkburges** [comment]
Sql/commands used for recovery:

```sql
-- project_role
select * from aatams.project_role where person_id in (select id from aatams.sec_user where name like '%Boomer%')

-- recoveries
select * from aatams.receiver_recovery where recoverer_id in (select id from aatams.project_role where person_id in (select id from aatams.sec_user where name like '%Boomer%'))

**Comment by jkburges** [comment]
@kereid I *think* the data is restored in production now, but can you please get Andre to check from his end.  I haven't done anything around the deleted users (in terms of restoring data) - so he might want to do some extra checking there (i.e. were there any uploads, recoveries etc "owned" by those users).

As far as the unrecovered deployments for AATAMS Heron Island, there are still some but they are for deployments which were deployed mid-way through 2014 so it's probably that they're still in the water (i.e. it's correct that the DB has them as "unrecovered").

**Comment by kereid** [comment]
Andre has responded that it all looks good and to let all know involved he is very sorry - should have checked first.

**Comment by astecken** [comment]
I think this issue is easily resolved by changing read/write access of people which I should have done in the first place. I think this issue can be closed (but I don't know how). :)

**Comment by jkburges** [comment]
A solution is outlined here: https://github.com/aodn/aatams/issues/257
