### ISSUE TITLE
Editing a tag results in a duplicate being created

### ISSUE THREAD

**Issue by kereid** [aodn/aatams#209]
Alicia Schmit-Roach originally reported this in #119 however it was such a convoluted issue that it got closed with the issue of duplication still outstanding.

Steps to reproduce:

Go into a tag to edit that is entered as a pinger and change to accelerometer or pressure. 

What should happen:

Tag is updated

What does happen:

Tag is saved as a duplicate.

These are some Tags Alicia has sent through that she needs to update.The first in the list IS already in the database twice, and Andrew deleted duplicates for: 
A69-9002- 14734, serial number: 1127333
A69-9002- 10420, serial number: 1177659
A69-9002- 14714, serial number: 1127378
A69-1105-170, serial number: 1138523 
previously, so she hadn't put any more in since.

![first in list of duplicates](https://cloud.githubusercontent.com/assets/2906602/6568577/3a8be23a-c72e-11e4-81f6-0174d68de065.jpg)

**Comment by xhoenner** [comment]
This bug might cause some of the duplicates observed in https://github.com/aodn/aatams/issues/240, might be worth looking at these two issues together.

**Comment by xhoenner** [comment]
@julian1 has set up a test instance of the web app and db for us to play with @astecken. Let's try and re-create that bug when I'm at SIMS as I haven't managed to do that myself.

**Comment by kereid** [comment]
I wrote to Alicia yesterday to ask if she still sees this issue, but my interpretation is that she hasn't needed to enter data since reporting the issue in 2014 and did enter all the data then. So if it can't be reproduced then perhaps changes since then have resulted in this issue being rectified.

Alicia's email from yesterday:

If I remember correctly the problem I was having in 2014 was that the tags were duplicating in the database if I updated them, but just the sensor tags I believe. I had the same problem when I was trying to add the tag life information to the tags on the database. I'm not sure if it is working now. But that’s why some of the tags are duplicated in the database. The list I sent you has everything I entered, which is all the tags but not all the tag life information and animal information. Hope this makes sense and was helpful. Let me know if you need more information.

**Comment by xhoenner** [comment]
Thanks @kereid for chasing that up. Since we weren't able to recreate this issue yesterday on the AATAMS test instance I'll close this issue.
