### ISSUE TITLE
Add total detections to Tag Detection List

### ISSUE THREAD

**Issue by ktattersall** [aodn/aatams#211]
In the AATAMS web app, Andre has requested that the total number of detections (of each tag, or for each receiver?) be added to the 'Tag Detection List'. I have emailed him for more information.

**Comment by ktattersall** [comment]
Update: "You know how we could always see the TOTAL number of detections of the whole database in that section in the past, e.g. 54 million? With the last release the view has changed so that it only displays the first 100 records only and the total number is no longer visible at the top"

**Comment by astecken** [comment]
test

**Comment by xhoenner** [comment]
Refer to https://github.com/aodn/aatams/issues/156

**Comment by xhoenner** [comment]
This is the same issue as https://github.com/aodn/aatams/issues/156.
