### ISSUE TITLE
Overlapping initialisation dates create duplicate detections

### ISSUE THREAD

**Issue by xhoenner** [aodn/aatams#223]
Seen on aatams.emii.org.au, app version 3.14.2. This bug may creates a significant amount of duplicates (SELECT COUNT(*) FROM valid_detection returns 69.5 million rows, versus 63.1 millions in the last [report](http://imos.org.au/fileadmin/user_upload/shared/emii/May15_AATAMS_acousticTagging_summary_project.pdf)) which negatively impact the reporting and the underlying harvester.

<h3> Steps to reproduce <h3>

Run the following query:

`SELECT *
  FROM aatams.valid_detection WHERE detection_id = 4523`;

<h3> What happens? <h3>

Getting the same detection_id twice (detection timestamp = "2011-01-02 00:20:34+00") in the `detection_view` and `valid_detection` views, one being erroneous as it doesn't use the receiver deployment date. 

<h3> What should happen? <h3>

Based on the details we have for the VR2W-103394 receiver (see image below), that detection_id should only be associated with the deployment of this receiver at Hawks Nest,NSW.

Additionally,

* the app should disallow overlapping deployments from being entered
* the receiver screen should include an initialisation date column (since that's the value being used as the start of the deployment date range)

![screen shot 2015-06-23 at 3 04 00 pm](https://cloud.githubusercontent.com/assets/3443821/8299258/6d0036b6-19b9-11e5-91da-2301159a4a02.jpg)

Looking more closely at the information available for this receiver, @jkburges identified that this bug is due to overlapping initialisation dates.

<i> Deployment at Hawks Nest <i>

Initialisation Date	2010-10-01T09:00:00+1000
Deployment Date	2010-10-28T08:30:00+1100
Recovery Date	2011-03-08T08:16:00+1100

<i> Deployment at AATAMS Port Stephens <i>

Initialisation Date	2010-10-27T10:15:24+0000
Deployment Date	2011-03-09T05:36:00+0000
Recovery Date	2012-06-22T12:45:00+1000

**Comment by jkburges** [comment]
A query to identify overlapping deployments (based on the interval of initialisation date to recovery date):

```sql
set search_path to 'aatams';

-- CTE with a proper range type (tstzrange) - then we can use the 'overlaps' (&&) operator below.
with deployments as (
  select *, tstzrange(initialisationdatetime_timestamp, recoverydatetime_timestamp) as deployment_interval from deployment_and_recovery
  join receiver on deployment_and_recovery.receiver_id = receiver.id
  where initialisationdatetime_timestamp is not null and recoverydatetime_timestamp is not null
  and initialisationdatetime_timestamp <= recoverydatetime_timestamp
)

select 
  lhs.receiver_id, lhs.receiver_name,
  lhs.deployment_interval as lhs_deployment_interval,
  rhs.deployment_interval as rhs_deployment_interval,
  'https://aatams.emii.org.au/aatams/receiver/show/' || lhs.receiver_id as receiver_url
from deployments lhs
join deployments rhs
  on lhs.receiver_name = rhs.receiver_name
  and lhs.deployment_interval && rhs.deployment_interval
  and lhs.receiver_deployment_id != rhs.receiver_deployment_id
  and lhs.initialisationdatetime_timestamp < rhs.initialisationdatetime_timestamp
order by lhs.receiver_name, lhs.initialisationdatetime_timestamp
```

There are 447 overlaps, so we might have to think of a way to automatically correct this data (probably based on the deployment date), rather than doing it manually.

**Comment by jkburges** [comment]
A query to count the number of `detection` record which match up with overlapping deployments (6,925,266 at the time of writing):

```sql
set search_path to 'aatams';

-- CTE with a proper range type (tstzrange) - then we can use the 'overlaps' (&&) operator below.
with deployments as (
  select *, tstzrange(initialisationdatetime_timestamp, recoverydatetime_timestamp) as deployment_interval from deployment_and_recovery
  join receiver on deployment_and_recovery.receiver_id = receiver.id
  where initialisationdatetime_timestamp is not null and recoverydatetime_timestamp is not null
  and initialisationdatetime_timestamp <= recoverydatetime_timestamp
)

select count(*)
from deployments lhs
join deployments rhs
  on lhs.receiver_name = rhs.receiver_name
  and lhs.deployment_interval && rhs.deployment_interval
  and lhs.receiver_deployment_id != rhs.receiver_deployment_id
  and lhs.initialisationdatetime_timestamp < rhs.initialisationdatetime_timestamp
join detection
  on lhs.receiver_name = detection.receiver_name
  and (detection.timestamp <@ (lhs.deployment_interval * rhs.deployment_interval));
```

**Comment by jkburges** [comment]
Following is a proposal to fix this issue, please comment @xhoenner @pblain.

Part A (can be done straight away)
1. Fix the validation so that overlapping deployments can no longer be entered
1. Add the 'initialisation' date column to the receiver screen (this will help with the steps below)
1. Deploy

Part B (requires input from data providers, i.e. Andre and perhaps others)
Meanwhile,

1. Work with Andre to determine the best way of correcting the currently invalid data.  It's probably not feasible to manually fix all 774 overlaps.  It *may* be possible to come up with an heuristic (see below) to fix the majority of the data, but I'm not sure.

An example fix heuristic could be: for every overlap, reset the initialisation date to be equal to the overlapped deployment's recovery date.  Whether or not this is accurate enough is not for me to say.

**Comment by pblain** [comment]
@jkburges - sounds good to me.  Feel free to start on Part A.  Xav (or Kath) will need to talk to Andre about Part B.

**Comment by xhoenner** [comment]
@jkburges sounds good to me as well, some comments below.

> Add the 'initialisation' date column to the receiver screen (this will help with the steps below)

Not sure I understand how this will help @astecken, can you be more specific?

> It's probably not feasible to manually fix all 774 overlaps.

Agreed, and your heuristic fix sounds like an adequate band aid for now, until we hear what @astecken thinks of having the initialisation date = deployment date.

Just to make sure we've got this right, are there 447 or 774 overlaps?

**Comment by jkburges** [comment]
> > Add the 'initialisation' date column to the receiver screen (this will help with the steps below)

> Not sure I understand how this will help @astecken, can you be more specific?

The receiver screen is useful because it enables you to see *all* deployments for a particular receiver on the one screen. 

However, it currently only shows deployment and recovery date, not initialisation date.  It'd be useful when correcting data (I would think) to see the initialisation date here since that's the one that matters as far as matching detections to a deployment is concerned.

> Just to make sure we've got this right, are there 447 or 774 overlaps?

Sorry, it's 447 :-)

**Comment by xhoenner** [comment]
> However, it currently only shows deployment and recovery date, not initialisation date. It'd be useful when correcting data (I would think) to see the initialisation date here since that's the one that matters as far as matching detections to a deployment is concerned.

Makes perfect sense yes, thanks Jon for clearing that up.

**Comment by astecken** [comment]
It makes all sense to me to. Feel free to go ahead with proposed changes. 

Also, to keep in mind for implementing automatic data upload in the future: It is probably easiest to use 'initialisation time' for 'deployment time' and 'data upload' time as 'recovery time' if that makes sense.

**Comment by jkburges** [comment]
@astecken even if we go ahead with the 'auto-correct' described above, we're still going to end up with a few (~60) that still overlap (that's based on setting init date = deployment date) - so we're still possibly going to need some help from you to correct those ones - but we'll let you know.

**Comment by astecken** [comment]
No worries.

**Comment by jkburges** [comment]
Code changes have been made to stop invalid records making it in to the DB.  Closing this issue, but have opened https://github.com/aodn/aatams/issues/241 which specifically addresses Part B from above.
