### ISSUE TITLE
Changes made to the AATAMS database structure impact the harvester used for reporting 

### ISSUE THREAD

**Issue by xhoenner** [aodn/aatams#224]
@jkburges suggested I open a new issue in the hope of having one day the SQL queries I use for reporting as part of the tests that are run before modifying the database structure. For instance the last update made the reporting harvester fail due to one field from the valid_detection view being renamed from id to detection_id.

Here are below the queries used for each report. It's important to note that those queries don't get run on the production database, instead I copy a subset of the data that's needed for the reporting into the dw_aatams_acoustic schema in dbprod. For a more comprehensive picture of the work involved to get the information needed for the reports, refer to the [AATAMS_ACOUSTIC_REPORTING harvester] (https://github.com/aodn/harvesters/tree/master/workspace/AATAMS_ACOUSTIC_REPORTING), more specifically the `Copy_Tables` and `Populate_reporting_views` subjobs.

<b><i> AATAMS_acousticTagging_allSpecies.pdf <i><b>

SELECT ar.id AS animal_release_id,
	p.name AS project_name,
	s.phylum,
	s.order_name,
	s.common_name,
	ar.release_locality,
	date(ar.embargo_date) AS embargo_date,
	COUNT(vd.timestamp) AS no_detections,
	date(min(vd.timestamp)) AS first_detection,
	date(max(vd.timestamp)) AS last_detection,
	round((date_part('days', max(vd.timestamp) - min(vd.timestamp)) + date_part('hours', max(vd.timestamp) - min(vd.timestamp))/24)::numeric, 1) AS coverage_duration
  FROM valid_detection vd
  LEFT JOIN sensor on vd.transmitter_id = sensor.transmitter_id
  LEFT JOIN device d on sensor.tag_id = d.id
  JOIN surgery su ON su.tag_id = d.id
  FULL JOIN animal_release ar ON su.release_id = ar.id
  JOIN animal a ON ar.animal_id = a.id
  JOIN species s ON a.species_id = s.id
  JOIN project p ON p.id = ar.project_id
	GROUP BY ar.id, p.name, s.phylum, s.order_name, s.common_name, ar.embargo_date
	ORDER BY animal_release_id, phylum,order_name,common_name;

<b><i> AATAMS_acousticTagging_summary_species.pdf <i><b>

<i> For the report itself <i>

WITH a AS (
  SELECT common_name,
	COUNT(DISTINCT transmitter_id) AS no_individuals_public,
	SUM(no_detections) AS no_detections_public
  FROM aatams_acoustic_detections_map
  WHERE common_name IS NOT NULL
	GROUP BY common_name)
  SELECT v.phylum,
	v.order_name,
	v.common_name,
	COUNT(DISTINCT v.project_name) AS no_projects,
	COUNT(DISTINCT v.release_locality) AS no_localities,
	COUNT(v.animal_release_id) AS no_releases,
	SUM (CASE WHEN v.embargo_date > now() THEN 1 ELSE 0 END) AS no_embargo,
	SUM (CASE WHEN v.no_detections = 0 THEN 0 ELSE 1 END) AS no_releases_with_detections,
	CASE WHEN no_individuals_public IS NULL THEN 0 ELSE no_individuals_public END AS no_public_releases_with_detections,
	max(v.embargo_date) AS latest_embargo_date,
	SUM(v.no_detections) AS total_no_detections,
	CASE WHEN no_detections_public IS NULL THEN 0 ELSE no_detections_public END AS no_detections_public,
	min(v.first_detection) AS earliest_detection,
	max(v.last_detection) AS latest_detection,
	round(avg(v.coverage_duration)::numeric, 1) AS mean_coverage_duration
  FROM aatams_acoustic_species_all_deployments_view v
  FULL JOIN a ON v.common_name = a.common_name
	GROUP BY v.phylum, v.order_name, v.common_name, no_individuals_public, no_detections_public
	ORDER BY phylum, order_name, common_name;

<i> For the totals in that report <i>

WITH total_species AS (
  SELECT COUNT(*) AS t,
	'total no tagged species' AS statistics_type
  FROM aatams_acoustic_species_data_summary_view),
total_species_public AS(
  SELECT COUNT(*) AS t, 
	'no tagged species for which all animals are public' AS statistics_type
  FROM aatams_acoustic_species_data_summary_view
    WHERE no_embargo = 0),
total_species_embargo AS (
  SELECT COUNT(*) AS t,
	'no tagged species for which some animals are currently under embargo' AS statistics_type
  FROM aatams_acoustic_species_data_summary_view
  WHERE no_embargo != 0),
total_species_detections AS (
    SELECT COUNT(*) AS t,
	'no tagged species with detections' AS statistics_type
  FROM aatams_acoustic_species_data_summary_view
  WHERE total_no_detections != 0),
total_species_public_detections AS (
    SELECT COUNT(*) AS t,
	'no tagged species with public detections' AS statistics_type
  FROM aatams_acoustic_species_data_summary_view
  WHERE no_detections_public != 0),
total_species_embargo_detections AS (
    SELECT COUNT(*) AS t,
	'no tagged species with embargoed detections' AS statistics_type
  FROM aatams_acoustic_species_data_summary_view
  WHERE no_detections_public = 0 AND total_no_detections != 0),
total_animals AS (
  SELECT SUM (no_releases) AS t,
	'total no tagged animals' AS statistics_type
  FROM aatams_acoustic_species_data_summary_view),
total_animals_public AS (
  SELECT SUM (no_releases) - SUM(no_embargo) AS t, 
	'no tagged animals that are public' AS statistics_type
  FROM aatams_acoustic_species_data_summary_view),
total_animals_embargo AS (
  SELECT SUM(no_embargo) AS t, 
	'no tagged animals currently under embargo' AS statistics_type
  FROM aatams_acoustic_species_data_summary_view),
total_animals_detections AS (
    SELECT SUM (no_releases_with_detections) AS t,
	'no tagged animals with detections' AS statistics_type
  FROM aatams_acoustic_species_data_summary_view),
total_animals_public_detections AS (
    SELECT SUM (no_public_releases_with_detections) AS t,
	'no tagged animals with public detections' AS statistics_type
  FROM aatams_acoustic_species_data_summary_view),
total_animals_embargo_detections AS (
    SELECT SUM(no_releases_with_detections) - SUM(no_public_releases_with_detections) AS t,
	'no tagged animals with embargoed detections' AS statistics_type
  FROM aatams_acoustic_species_data_summary_view),
total_detections AS (
  SELECT SUM (total_no_detections) AS t,
	'no detections' AS statistics_type
	FROM aatams_acoustic_species_data_summary_view),
total_detections_public AS (
  SELECT SUM (no_detections_public) AS t,
	'no detections that are public' AS statistics_type
	FROM aatams_acoustic_species_data_summary_view),
total_detections_embargo AS (
  SELECT SUM (total_no_detections) - SUM (no_detections_public) AS t,
	'no detections that are currently under embargo' AS statistics_type
	FROM aatams_acoustic_species_data_summary_view),
tag_ids AS (
  SELECT COUNT(DISTINCT transmitter_id) AS t,
	'no unique tag ids detected' AS statistics_type
  FROM valid_detection),
tag_aatams_knows AS (
  SELECT COUNT(*) AS t,
	'tag aatams knows about' AS statistics_type
  FROM device 
	WHERE class = 'au.org.emii.aatams.Tag'),
detected_tags_aatams_knows AS (
  SELECT COUNT(DISTINCT sensor.transmitter_id) AS t,
	'no detected tags aatams knows about' AS statistics_type
  FROM valid_detection 
  JOIN sensor ON valid_detection.transmitter_id = sensor.transmitter_id),
tags_by_species AS (
  SELECT COUNT(DISTINCT s.tag_id) AS t,
	'tags detected by species' AS statistics_type
  FROM valid_detection vd
  LEFT JOIN sensor on vd.transmitter_id = sensor.transmitter_id
  LEFT JOIN device d on sensor.tag_id = d.id
  JOIN surgery s ON s.tag_id = d.id),
embargo_1 AS (
  SELECT COUNT(*) AS t, 
	'Total number of tags embargoed for less than or equal to a year' AS statistics_type
  FROM animal_release ar
  WHERE ROUND((EXTRACT (day FROM embargo_date - releasedatetime_timestamp)/365.25)::numeric,1) <= 1 AND ROUND((EXTRACT (day FROM embargo_date - releasedatetime_timestamp)/365.25)::numeric,1) IS NOT NULL),
embargo_2 AS (
  SELECT COUNT(*) AS t, 
	'Total number of tags embargoed for more than a year, but less than or equal to 2 years' AS statistics_type
  FROM animal_release ar
  WHERE ROUND((EXTRACT (day FROM embargo_date - releasedatetime_timestamp)/365.25)::numeric,1) > 1 AND ROUND((EXTRACT (day FROM embargo_date - releasedatetime_timestamp)/365.25)::numeric,1) <= 2
  AND ROUND((EXTRACT (day FROM embargo_date - releasedatetime_timestamp)/365.25)::numeric,1) IS NOT NULL),
embargo_3 AS (
  SELECT COUNT(*) AS t,
	'Total number of tags embargoed for more than two years, but less than or equal to 3 years' AS statistics_type
  FROM animal_release ar
  WHERE ROUND((EXTRACT (day FROM embargo_date - releasedatetime_timestamp)/365.25)::numeric,1) > 2 AND ROUND((EXTRACT (day FROM embargo_date - releasedatetime_timestamp)/365.25)::numeric,1) <= 3
  AND ROUND((EXTRACT (day FROM embargo_date - releasedatetime_timestamp)/365.25)::numeric,1) IS NOT NULL),
embargo_3_more AS (
  SELECT COUNT(*) AS t,
	'Total number of tags embargoed for more than three years' AS statistics_type
  FROM animal_release ar
  WHERE ROUND((EXTRACT (day FROM embargo_date - releasedatetime_timestamp)/365.25)::numeric,1) > 3 AND ROUND((EXTRACT (day FROM embargo_date - releasedatetime_timestamp)/365.25)::numeric,1) IS NOT NULL)
  SELECT 'Species' AS type, 
	s.t AS total, 
	sp.t AS total_public,
	se.t AS total_embargo, 
	sd.t AS detections_total, 
	spd.t AS detections_public, 
	sed.t AS detections_embargo,
	NULL::bigint AS other_1,
	NULL::bigint AS other_2
  FROM total_species s, total_species_public sp,total_species_embargo se, total_species_detections sd, total_species_public_detections spd,total_species_embargo_detections sed
UNION ALL
  SELECT 'Animals' AS type, 
	a.t AS total, 
	ap.t AS total_public,
	ae.t AS total_embargo, 
	ad.t AS detections_total, 
	apd.t AS detections_public, 
	aed.t AS detections_embargo,
	NULL AS other_1,
	NULL AS other_2
  FROM total_animals a, total_animals_public ap,total_animals_embargo ae, total_animals_detections ad, total_animals_public_detections apd,total_animals_embargo_detections aed
UNION ALL
  SELECT 'Detections' AS type, 
	NULL AS total, 
	NULL AS total_public,
	NULL AS total_embargo, 
	d.t AS detections_total, 
	dp.t AS detections_public, 
	de.t AS detections_embargo,
	NULL AS other_1,
	NULL AS other_2
  FROM total_detections d, total_detections_public dp, total_detections_embargo de	
UNION ALL
  SELECT 'Other stats' AS type,
	ti.t AS total, 
	ta.t AS total_public,
	dta.t AS total_embargo, 
	ts.t AS detections_total, 
	e1.t AS detections_public, 
	e2.t AS detections_embargo,
	e3.t AS other_1,
	e3m.t AS other_2
  FROM tag_ids ti, tag_aatams_knows ta, detected_tags_aatams_knows dta, tags_by_species ts, embargo_1 e1, embargo_2 e2, embargo_3 e3, embargo_3_more e3m;

------------------------------------------------------------------------------------------------------------------------

<b><i> AATAMS_acousticTagging_allProjects.pdf <i><b>

SELECT CASE WHEN substring(p.name,'AATAMS')='AATAMS' THEN 'IMOS funded and co-invested' 
	      WHEN p.name = 'Coral Sea  Nautilus tracking project' 
	      OR p.name = 'Seven Gill Tracking in Coastal Tasmania' 
	      OR substring(p.name,'Yongala')='Yongala' 
	      OR p.name = 'Rowley Shoald reef shark tracking 2007' 
	      OR p.name = 'Wenlock River Array, Gulf of Carpentaria' THEN 'IMOS Receiver Pool' 
	      ELSE 'Fully Co-Invested' END AS funding_type,
	p.id AS project_id,
	p.name AS project_name,
	i.name AS installation_name,
	ist.name AS station_name,
	COUNT(DISTINCT rd.id) AS no_deployments,
	COUNT(vd.timestamp) AS no_detections,
	min(rd.deploymentdatetime_timestamp) AS first_deployment_date,
	max(rd.deploymentdatetime_timestamp) AS last_deployment_date,
	min(vd.timestamp) AS start_date,
	max(vd.timestamp) AS end_date,
	round((date_part('days', max(vd.timestamp) - min(vd.timestamp)) + date_part('hours', max(vd.timestamp) - min(vd.timestamp))/24)::numeric, 1) AS coverage_duration,
	ROUND(st_y(ist.location)::numeric,1) AS station_lat,
	ROUND(st_x(ist.location)::numeric,1) AS station_lon,
	ROUND(min(rd.depth_below_surfacem::integer),1) AS min_depth,
	ROUND(max(rd.depth_below_surfacem::integer),1) AS max_depth
  FROM project p
  FULL JOIN installation i ON i.project_id = p.id
  FULL JOIN installation_station ist ON ist.installation_id = i.id
  FULL JOIN receiver_deployment rd ON rd.station_id = ist.id
  FULL JOIN valid_detection vd ON vd.receiver_deployment_id = rd.id
	GROUP BY p.id, p.name,i.name,ist.name,ist.location
	ORDER BY project_name,installation_name,station_name;

<b><i> AATAMS_acousticTagging_summary_project.pdf <i><b>

<i> For the report itself <i>

WITH a AS (SELECT project_id, COUNT(DISTINCT ar.id) AS no_releases FROM animal_release ar GROUP BY project_id)
  SELECT funding_type,
	project_name,
	COUNT (DISTINCT(installation_name))::numeric AS no_installations,
	COUNT (DISTINCT(station_name))::numeric AS no_stations,
	SUM(no_deployments)::numeric AS no_deployments,
	ROUND(AVG(a.no_releases),0) AS no_releases,
	SUM(no_detections) AS no_detections,
	min(first_deployment_date) AS earliest_deployment_date,
	max(last_deployment_date) AS latest_deployment_date,
	min(start_date) AS start_date,
	max(end_date) AS end_date,
	round((date_part('days', max(end_date) - min(start_date)) + date_part('hours', max(end_date) - min(start_date))/24)::numeric, 1) AS coverage_duration,
	min(station_lat) AS min_lat,
	max(station_lat) AS max_lat,
	min(station_lon) AS min_lon,
	max(station_lon) AS max_lon,
	min(min_depth) AS min_depth,
	max(max_depth) AS max_depth
  FROM aatams_acoustic_project_all_deployments_view v
  LEFT JOIN a ON a.project_id = v.project_id
	GROUP BY funding_type,project_name
	ORDER BY funding_type DESC,project_name;

<i> For the totals in that report <i>

SELECT funding_type,
	COUNT(DISTINCT(project_name)) AS no_projects,
	SUM(no_installations) AS no_installations,
	SUM(no_stations) AS no_stations,
	SUM(no_deployments) AS no_deployments,
	SUM(no_releases) AS no_releases,
	SUM(no_detections) AS no_detections
  FROM aatams_acoustic_project_data_summary_view
	GROUP BY funding_type
UNION ALL
  SELECT 'TOTAL' AS funding_type,
	COUNT(DISTINCT(project_name)) AS no_projects,
	SUM(no_installations) AS no_installations,
	SUM(no_stations) AS no_stations,
	SUM(no_deployments) AS no_deployments,
	SUM(no_releases) AS no_releases,
	SUM(no_detections) AS no_detections
  FROM aatams_acoustic_project_data_summary_view
	ORDER BY funding_type ASC;

**Comment by jkburges** [comment]
Are the queries above updated w.r.t. to the recent change to the DB, or are they broken?

**Comment by xhoenner** [comment]
All the above queries should be working. The query that makes the harvester fail is in the `Copy_Tables` subjob:
```SELECT id, receiver_deployment_id, timestamp, transmitter_id FROM aatams.valid_detection;```

It doesn't work for two reasons: 
* id has been changed to detection_id (easy change for me to make),
* there are now duplicate detection_id (problematic as I have a primary key on that field).

**Comment by xhoenner** [comment]
This has now been implemented here https://github.com/aodn/aatams/tree/master/test/integration/au/org/emii/aatams/monthlyreport.
