### ISSUE TITLE
Deployments with null initialisation date

### ISSUE THREAD

**Issue by jkburges** [aodn/aatams#225]
Some deployments have a null initialisation date.  Probably, they were entered before the system had the concept of initialisation date.

This was discovered whilst following up on https://github.com/aodn/aatams/issues/223

We can probably fix the issue by just setting the initialisation date equal to the deployment date in these cases.

**Steps to reproduce**
```sql
select * from receiver_deployment
where initialisationdatetime_timestamp is null
```

**What happens?**

Some results are returned (9 at the time of writing).

**What should happen?**

There should be 0 results.

**Comment by xhoenner** [comment]
There are now 36 results instead of 9 for the above query. The additional results returned are from recent receiver deployments (last couple of months), suggesting that there's still an issue with the way initialisation dates are being configured in the system.

@jkburges I'm happy to work on an ad hoc SQL query to set null initialisation dates to be equal to deployment dates, but, this probably requires more investigation anyway. What do you think?

**Comment by jkburges** [comment]
I think my original bug report here is a bit misleading.  I think it's ok for deployments to have a null initialisation date, so long as there *is no associated recovery*, as that's when the initialisation date is filled in by the user.

So the query should also check that there is no associated recovery (probably a `left join receiver_recovery` and a where clause checking that `receiver_recovery.is is null`, or some such)

**Comment by jkburges** [comment]
As far as fixing it goes, I think this is another case where @astecken should really make the call, as he's got a much better idea of what these values *should* be (at least compared to me)!

**Comment by xhoenner** [comment]
Thanks for clarifying that Jon, running the following query returns 9 records:

```sql
select * from aatams.receiver_deployment rd
LEFT JOIN aatams.receiver_recovery rr ON rr.deployment_id = rd.id
where initialisationdatetime_timestamp is null AND rr.id is NOT null
```

@astecken are you happy for us to fix those by setting all null initialisation dates to be equal to deployment dates?

**Comment by astecken** [comment]
Xavier, could you sen me a list of those 9 records, pls, so I can check when they were deployed and recovered? If it is the case that 
'Some deployments have a null initialisation date. Probably, they were entered before the system had the concept of initialisation date.' 
then I think it would be ok to set 
'all null initialisation dates to be equal to deployment dates'.

**Comment by xhoenner** [comment]
No worries Andre, have a look at these 9 records (https://drive.google.com/file/d/0B0gOwvJSYXhsVTdyVHlSdDFBdFE/view?usp=sharing) and let me know what you want us to do.

**Comment by astecken** [comment]
I think, we should go ahead and change those as suggested above. Thanks!

**Comment by xhoenner** [comment]
great, thanks Andre. @jkburges how should we proceed? Do you want me to work on the SQL query to fix that up?

**Comment by jkburges** [comment]
Given that there are only 9 affect records, can't it be done from the front-end?  This ensures that what ends up in there is actually valid (bugs aside!), apart from being a bit safer than write-queries directly on the DB.

**Comment by xhoenner** [comment]
That makes perfect sense Jon, are you happy to do that @astecken? If so, let me know once it's done so that I can close this issue.

**Comment by jkburges** [comment]
@astecken may need a list of URLs (to the recoveries in question) if he's to do it.

It'll be of the form "https://aatams.emii.org.au/aatams/receiverRecovery/show/<id from receiver_recovery table>"

**Comment by astecken** [comment]
Done. Would you mind to run the query again just to see if there's anything left? If not, you can close this issue.

**Comment by jkburges** [comment]
:+1: @astecken - no results from [the query above](https://github.com/aodn/aatams/issues/225#issuecomment-132096652) - good work!
