### ISSUE TITLE
AATAMS baseload relatively high

### ISSUE THREAD

**Issue by danfruehauf** [aodn/aatams#229]
1 cpu occupied most of the time, probably due to crawling:
https://nagios.aodn.org.au/pnp4nagios/graph?host=3-aws-syd.emii.org.au&srv=cpu&view=1&start=&end=

**Comment by danfruehauf** [comment]
A potential quick fix for that is #228

**Comment by jkburges** [comment]
Just to expand, the underlying cause of this is that hitting the 'receiverEvent' page triggers a `count` of the underlying table - a relatively expensive operation.  We can probably do without this functionality, as we have done with detections.
