### ISSUE TITLE
Simplified AATAMS proposal

### ISSUE THREAD

**Issue by jkburges** [aodn/aatams#244]
Shifted to https://github.com/aodn/internal_discussions/issues/147

**Comment by pblain** [comment]
Sounds good to me.  It's similar to my original proposal but it solves the issue with embargoed data: https://github.com/aodn/internal_discussions/issues/129

I assume you are suggesting that the security is managed in the database?

What is the extra work for POs?  There will be another couple of harvesters - but is there more to it?  There will need to be harvesters anyway - even if we stick with the webapp.

**Comment by jkburges** [comment]
> It's similar to my original proposal

Yes, it is - it builds on from that.  Aside from *what* form the implementation takes, I guess the point I really wanted to get across with this proposal is that it's important to reduce the complexity in order to reduce workload - an orthogonal proposition to web app vs harvester etc. 

> I assume you are suggesting that the security is managed in the database?

Yes - because the security logic is very much simplified (i.e. not dependent on user/project etc) then the implementation can be as simple as:

```
if (row.embargo_date > current_date) {
  // not visible
}
else {
  // rainbow unicorns
}
```

Quite easy to implement (and test!) in SQL.

TBH, I'm quite sceptical as to how workable the management of the metadata is in this proposal, but it's worth discussing at least.

**Comment by jkburges** [comment]
> What is the extra work for POs?

Metadata will be managed by POs, rather than "self-service" by the data providers (+ harvesters, as you mention).

**Comment by smancini** [comment]
An additional table with the species information will also be required.
Otherwise, the user will download detection information without knowing what species it is related to.

You are proposing that the receiver deployment and tag releases tables are managed manually but currently there are no other facilities where database tables are managed manually.
The only examples are reporting, parameters mapping and controlled vocabulary (now obsolete) where Xavier and I have been granted access to update tables manually.

**Comment by jkburges** [comment]
> the species information will also be required

Thanks @smancini - I have added the species info in.

> You are proposing that the receiver deployment and tag releases tables are managed manually but currently there are no other facilities where database tables are managed manually.

This information has to come from *somewhere*.  Without at least this basic metadata, the detections records are pretty useless (there will be no associated geographic location, for instance).

**Comment by xhoenner** [comment]
Some other cons that are not listed in Jon's proposal:
* Loss of interoperability with OTN and other agencies.
* Dropping the security would result in losing many users and their data.
* Waste of the resources that have been put together to build the AATAMS web app to its current state + high resources initially required to strip the system down entirely.
* Increased workload for @astecken and POs who will have to manage metadata manually to make sure they're in the right format. TBH if it comes to that I'd rather spend my time contributing to the AATAMS web app code by learning Grails and other computer languages than being the one in charge of looking after 1000s of tag and receiver metadata (about 4300 and 6300 metadata rows respectively).

Some additional metadata would be required for each tag release including sex, measurements. Similarly for receiver deployments we would need station name, installation name, project name, and the name and contact details of the principal investigator.

@jkburges what would be the point for users to put an embargo on their tags if they can't download any of their data?

**Comment by jkburges** [comment]
> what would be the point for users to put an embargo on their tags if they can't download any of their data?

Just to be clear - anything that is "hidden" currently would remain hidden - except more so.  The point of users uploading embargoed tags is that the information is shared albeit not visible until some time has elapsed.  Granted, there's probably not much motivation for people to do this unless they have some obligation (due to funding or whatnot) to do so.

> Some additional metadata would be required

We can keep adding in bits and pieces of metadata until eventually this stripped down DB has the same information as the current one - at which point we are no better off - so (if we go down this long, windy and narrow road) we need to be pretty careful about what we include.

**Comment by astecken** [comment]
Before this discussion goes any further, I strongly suggest that we will have a proper meeting with all involved parties incl. the chairs of the AATAMS Data and Scientific Committee and Rob as the Project Leader. As we all know, IMOS had major funding cuts and this will result in significant changes for us all (as discussed briefly with Roger on my last visit).

**Comment by ktattersall** [comment]
@astecken Thanks for your comment. At the moment, as Jon says at the top, this is purely a hypothetical scenario, and probably should have been posted as an internal eMII discussion rather than a public AATAMS issue. I'll see if I can shift the privacy settings. The discussion arose following a tightening of developer resources within our group. I'll give you a call to expand on this.
