### ISSUE TITLE
Tag release reminder/link

### ISSUE THREAD

**Issue by astecken** [aodn/aatams#246]
We are aware of a number of cases where people have registered their tags and not realised that they also have to “release” them. A very explicit link on the tag registration page emphasising the need to “release” the tag would be useful.

**Comment by xhoenner** [comment]
Just to refine the above comment (and correct me if I'm wrong @astecken), what's needed here is to change the wording in the text highlighted in blue in the screenshot below taken after registering or updating a tag respectively via the [Tag creation page] (http://aatams-dev-instance/aatams/sensor/create) or [Tag index page] (http://aatams-dev-instance/aatams/tag/index). 

![screen shot 2016-07-13 at 12 20 24 pm](https://cloud.githubusercontent.com/assets/3443821/16789887/99fba478-48f4-11e6-97c6-3b829fea0c0f.jpg)

This should read instead "Tag "A180-1105-198550" registered/updated. If deployed, please add release information for this tag via the [Tag release page] (http://aatams-dev-instance/aatams/animalRelease/create)."

**Comment by astecken** [comment]
Yep, that should do it, @xhoenner. Thanks!

**Comment by xhoenner** [comment]
Ideally we could have an automated process sending an email reminder to tag owners for them to add release metadata if their tags have been detected.

**Comment by fjaine** [comment]
Good suggestion @xhoenner - or could a special statement be added to the automated emails sent to those researchers when detections for their 'unreleased' tags are uploaded? I'm thinking and extra column next to the 'data...' column with some something like:

"Deployment information for this tag has not been provided. Enter release details here [link to Tag release page]"

![automated email screenshot](https://cloud.githubusercontent.com/assets/22288128/19915075/a4960206-a0a7-11e6-9c8f-d2f1255fee68.png)

**Comment by xhoenner** [comment]
This would be unnecessary if merging the tag registration and release processes, https://github.com/aodn/aatams/issues/365

**Comment by xhoenner** [comment]
Closing as will become obsolete once #365 is being addressed
