### ISSUE TITLE
HTTP Status 500 error when searching for a tag serial number and clicking on Sensor

### ISSUE THREAD

**Issue by xhoenner** [aodn/aatams#247]
<h3> Steps to reproduce <h3>

Go to https://aatams.emii.org.au/aatams/ 
In the search facet on the left hand side of the screen, type the following serial number 1177659 (have also tried 1127378, 1127333, 1138523) and hit Enter.
Click on A69-9002-10420 (Sensor). 

<h3> What happens? <h3>

Doing so returns an HTTP 500 error
![screen shot 2015-07-31 at 12 57 42 pm](https://cloud.githubusercontent.com/assets/3443821/8999956/8cb398b6-3784-11e5-9501-f390f277cdac.jpg)

<h3> What should happen? <h3>

It should show all the associated information for that sensor. Additionally it seems that when clicking on A69-9002-10420 (Tag) it returns info about the sensor, not the tag.

**Comment by jkburges** [comment]
Fixed.
