### ISSUE TITLE
Error message in Database not very helpful 

### ISSUE THREAD

**Issue by kereid** [aodn/aatams#252]
This stems from a user enquiry that came to info@emii.org.au where the user was trying to upload some data from his receivers and got the same error a couple of times, it only stated 

Err Msg: System Error - Contact eMII

Upon conferring with Jon, the problem usually arises  when a user is using an old version of VUE (Vemco's desktop software for getting data off recievers) and it mucks up the format of the file. (User did write back to say he had new software but export setting was for old format) 

Steps to reproduce:

Use old version of VUE to upload file, 

What should happen:

Error message indicates old version being used?

What does happen:

See Err Msg: System Error - Contact eMII

**Comment by xhoenner** [comment]
Closing as redundant with https://github.com/aodn/aatams/issues/252, and more specifically https://github.com/aodn/aatams/issues/30#issuecomment-412378160
