### ISSUE TITLE
Error message when adding a sensor to existing tag

### ISSUE THREAD

**Issue by kereid** [aodn/aatams#253]
@astecken  reported the following:

Get the following error msg when adding a sensor to an existing tag (A69-9004-588):

	‘Property [status] of class [class au.org.emii.aatams.Tag] cannot be null’

Steps to reproduce:

Use the autocomplete tag ID dropdown to find the tag in question.

Select the i button for the relevant entry and then click edit, click add sensor and add information in the following fields:

*****Andre to enter more detail here******

Click create

What should happen:
New sensor is added to tag

What does happen:

See error Property [status] of class [class au.org.emii.aatams.Tag] cannot be null’

Also I noticed when trying to search for the tags in the free text on the left the 2 entries that I got if I clicked on them resulted in seeing the following error.

HTTP Status 500 - Error processing GroovyPageView: No such property: id for class: au.org.emii.aatams.DeviceStatus

type Exception report

message Error processing GroovyPageView: No such property: id for class: au.org.emii.aatams.DeviceStatus

description The server encountered an internal error that prevented it from fulfilling this request.

exception

org.codehaus.groovy.grails.web.pages.exceptions.GroovyPagesException: Error processing GroovyPageView: No such property: id for class: au.org.emii.aatams.DeviceStatus
Possible solutions: key
	org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:359)
	org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:275)
	org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:344)
	org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:272)
	org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:81)
	org.apache.shiro.grails.SavedRequestFilter.doFilter(SavedRequestFilter.java:55)
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	java.lang.Thread.run(Thread.java:745)

root cause

groovy.lang.MissingPropertyException: No such property: id for class: au.org.emii.aatams.DeviceStatus
Possible solutions: key
	gsp_aatams_sensorshow_gsp$_run_closure2.doCall(gsp_aatams_sensorshow_gsp.groovy:95)
	gsp_aatams_sensorshow_gsp$_run_closure2.doCall(gsp_aatams_sensorshow_gsp.groovy)
	gsp_aatams_sensorshow_gsp.run(gsp_aatams_sensorshow_gsp.groovy:116)
	org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:359)
	org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:275)
	org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:344)
	org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:272)
	org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:81)
	org.apache.shiro.grails.SavedRequestFilter.doFilter(SavedRequestFilter.java:55)
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	java.lang.Thread.run(Thread.java:745)

note The full stack trace of the root cause is available in the Not specified logs.

**Comment by astecken** [comment]
Here is a bit more detail:

Get the following error msg when adding a sensor to an existing tag (A69-9004-588):

‘Property [status] of class [class au.org.emii.aatams.Tag] cannot be null’
Steps to reproduce:

Use the autocomplete tag ID dropdown to find the tag in question.

Select the i button for the relevant entry (the accelerometer one (2nd entry)) and then click edit, click add sensor and add information in the following fields:

Transmitter Type: Pressure
Ping ID Code: 589

Click create

What should happen:
New sensor is added to tag

What does happen:

See error Property [status] of class [class au.org.emii.aatams.Tag] cannot be null’

**Comment by astecken** [comment]
Hi Jon,

I just saw your release 3.14.4. Does this mean, I can now add a sensor to an existing tag ID as outlined above?

**Comment by jkburges** [comment]
It's not *quite* released yet, it will be some time shortly after 17:00 today!
