### ISSUE TITLE
Allow users to be deactivated

### ISSUE THREAD

**Issue by jkburges** [aodn/aatams#257]
There are two use cases:

1. A user no longer can have or wants access to the DB altogether
2. As above, except at an individual project level

We cannot simply delete the user (or their associated project roles), as the user is still referenced in the system (e.g. as a recoverer), and deleting the user record would result in this associated data also being deleted.

The proper way to model this is to allow users to be `DEACTIVATED`.  This option already exists for `organisations` and `projects`, but not for `people`.

Deactivating someone should disallow their access to the system (or individual projects) and stop email notifications.

**Comment by astecken** [comment]
I recently had people asking me if I can deactivate their access to certain projects. I also have students entering data for certain projects. I would like to be able to take students off those projects when they are not longer working with us. Thanks!

**Comment by xhoenner** [comment]
This issue is part of #204.
