### ISSUE TITLE
Events CSV upload error

### ISSUE THREAD

**Issue by kereid** [aodn/aatams#261]
Steps to reproduce:
Upload an events csv

What should happen:
Upload is successful

What does happen:
Get an error 

![2015 09_data base error_event upload 2](https://cloud.githubusercontent.com/assets/2906602/9984882/fa0cc5ce-6063-11e5-997a-8e3305f2bd2f.jpg)

**Comment by jkburges** [comment]
Note: I think the upload is succeeding, it's just that this view is erroring.

**Comment by xhoenner** [comment]
@jkburges what's the status of this issue, https://github.com/aodn/aatams/issues/262, and https://github.com/aodn/aatams/issues/263? Can they be closed?

**Comment by jkburges** [comment]
> @jkburges what's the status of this issue, #262, and #263? Can they be closed?

None of these bugs can be closed, although #262 and #263 are *probably* duplicates (i.e. caused by the same underlying problem).

**Comment by jkburges** [comment]
This bug is probably easy to fix.  It's not stopping people from entering/uploading data.
