### ISSUE TITLE
Location field populated with incorrect co-ordinates

### ISSUE THREAD

**Issue by kereid** [aodn/aatams#269]
Reported by Phil McDowall

Hi Guys,

I was just entering data for the OTN Perth Line and found a potential bug. I created a new station PRT61 and entered the LAT long: -32.07082, 115.57277. I then went to deploy a receiver at the newly created station at the “create receiver deployment” page. I selected the station name from the drop down menu and the Location field pre populated with the following lat long: 22.999617 S , 113.766417 E . This Lat long belongs to 23rd Parallel East and is the default lat long when you open a “create receiver deployment” page.

Despite completing many deployments for this line, this was the only instance that I noticed this discrepancy.

**Comment by xhoenner** [comment]
Tested with @astecken and we weren't able to recreate this issue.
