### ISSUE TITLE
App taking 400% cpu in production

### ISSUE THREAD

**Issue by danfruehauf** [aodn/aatams#282]
Related to:
https://github.com/aodn/internal_discussions/issues/175

Obviously it prevents access to the app while this is ongoing.

**Comment by danfruehauf** [comment]
I can't quite tell whether it is user triggered or periodically triggered. Nothing too suspicious in the logs.

**Comment by jonescc** [comment]
Connection leak?  In thread dump below - all db connections are waiting to borrow from the pool.

[jstack-aatams.txt](https://github.com/aodn/aatams/files/68008/jstack-aatams.txt)

**Comment by xhoenner** [comment]
This issue hasn't resurfaced since late last year so we decided to close it.
