### ISSUE TITLE
Valid detections associated to upload errors

### ISSUE THREAD

**Issue by xhoenner** [aodn/aatams#284]
I was tasked by @astecken to extract the number of detections uploaded in the db through time so I came up with the following query.

```sql
SET SEARCH_PATH = aatams,public;

SELECT vd.receiver_download_id, rdf.import_date, su.email_address, rdf.err_msg, rdf.type, COUNT(vd.detection_id)
FROM valid_detection vd
JOIN receiver_download_file rdf ON vd.receiver_download_id = rdf.id
JOIN sec_user su ON su.id = rdf.requesting_user_id
GROUP BY vd.receiver_download_id, rdf.import_date, su.email_address, rdf.err_msg, rdf.type;
```

The results of this query show that 6.8 million detections in the `valid_detection` view come from 29 csv uploads that generated errors, see the table below.

receiver_download_id | import_date | email_address | err_msg | type | count
-------------------- | ----------- | ------------- | ------- | ---- | -----
225113 | 2011-12-20 04:17:40 | phil.mcdowall@sims.org.au | System Error - Contact eMII | DETECTIONS_CSV | 135293
822544 | 2012-01-11 04:32:44 | charlie.huveneers@flinders.edu.au | System Error - Contact eMII | DETECTIONS_CSV | 1173
900696 | 2012-01-13 03:21:05 | kathryn.lee@mq.edu.au | System Error - Contact eMII | DETECTIONS_CSV | 200866
1738575 | 2012-02-01 03:47:35 | Russ.Bradford@csiro.au | System Error - Contact eMII | DETECTIONS_CSV | 8051
5745659 | 2012-09-11 14:14:50 | andrew.boomer@sims.org.au | System Error - Contact eMII | DETECTIONS_CSV | 2688073
25715364 | 2012-10-30 04:28:11 | kathryn.lee@mq.edu.au | System Error - Contact eMII | DETECTIONS_CSV | 179306
25718367 | 2012-10-30 04:28:25 | kathryn.lee@mq.edu.au | System Error - Contact eMII | DETECTIONS_CSV | 167278
25727876 | 2012-10-30 04:28:52 | kathryn.lee@mq.edu.au | System Error - Contact eMII | DETECTIONS_CSV | 360224
25760713 | 2012-10-30 04:29:51 | kathryn.lee@mq.edu.au | System Error - Contact eMII | DETECTIONS_CSV | 148569
25790719 | 2012-10-30 04:30:38 | kathryn.lee@mq.edu.au | System Error - Contact eMII | DETECTIONS_CSV | 162055
25880731 | 2012-10-30 04:32:40 | kathryn.lee@mq.edu.au | System Error - Contact eMII | DETECTIONS_CSV | 240089
25987243 | 2012-10-30 04:34:56 | kathryn.lee@mq.edu.au | System Error - Contact eMII | DETECTIONS_CSV | 439243
46861521 | 2013-02-22 03:06:34 | jerom.stocks@industry.nsw.gov.au | System Error - Contact eMII | DETECTIONS_CSV | 2356
46865149 | 2013-02-22 03:07:09 | jerom.stocks@industry.nsw.gov.au | System Error - Contact eMII | DETECTIONS_CSV | 18841
46870155 | 2013-02-22 03:07:52 | jerom.stocks@industry.nsw.gov.au | System Error - Contact eMII | DETECTIONS_CSV | 3704
46884746 | 2013-02-22 03:08:42 | jerom.stocks@industry.nsw.gov.au | System Error - Contact eMII | DETECTIONS_CSV | 10862
51451599 | 2013-05-10 07:10:08 | kathryn.lee@mq.edu.au | System Error - Contact eMII | DETECTIONS_CSV | 269609
54208273 | 2013-05-10 11:03:45 | kathryn.lee@mq.edu.au | System Error - Contact eMII | DETECTIONS_CSV | 202992
54421492 | 2013-05-10 11:18:48 | kathryn.lee@mq.edu.au | System Error - Contact eMII | DETECTIONS_CSV | 147555
54563574 | 2013-05-10 11:24:59 | kathryn.lee@mq.edu.au | System Error - Contact eMII | DETECTIONS_CSV | 323823
70607154 | 2013-09-03 22:44:01 | james.vandenbroek@sims.org.au | System Error - Contact eMII | DETECTIONS_CSV | 10767
70608008 | 2013-09-03 22:47:26 | james.vandenbroek@sims.org.au | System Error - Contact eMII | DETECTIONS_CSV | 2146
70615542 | 2013-09-03 23:01:47 | james.vandenbroek@sims.org.au | System Error - Contact eMII | DETECTIONS_CSV | 6905
70632266 | 2013-09-04 00:29:46 | james.vandenbroek@sims.org.au | System Error - Contact eMII | DETECTIONS_CSV | 656788
100620560 | 2014-07-14 01:11:31 | 21197091@student.uwa.edu.au | Incorrect format for Date and Time (UTC) expected yyyy-MM-dd HH:mm:ss Z | DETECTIONS_CSV | 224317
109253904 | 2014-09-10 01:27:46 | sharon.marshall@dnrm.qld.gov.au | System Error - Contact eMII | DETECTIONS_CSV | 13119
112677656 | 2014-12-12 04:04:07 | sharon.marshall@dnrm.qld.gov.au | System Error - Contact eMII | DETECTIONS_CSV | 150577
112901684 | 2014-12-12 04:13:01 | sharon.marshall@dnrm.qld.gov.au | System Error - Contact eMII | DETECTIONS_CSV | 95652
113395646 | 2014-12-17 23:35:40 | andre.steckenreuter@sims.org.au | System Error - Contact eMII | DETECTIONS_CSV | 9

@jkburges, @dnahodil is that normal that those detections end up in the valid_detection view despite showing errors in the `receiver_download_file` table?

**Comment by jkburges** [comment]
The upload process is not transactional, that is, detections are loaded in to the DB progressively (in chunks) as the file is processed.  So probably what's happened here is that some have made it in before an error has occurred.

Those file upload errors are all from a pretty long time ago, so we're not going to have log files or anything to check exactly what's going on in any more detail.

You could try re-uploading (to a test system) one of them though perhaps to see if you can re-create the error?

**Comment by xhoenner** [comment]
Thanks @jkburges for those details, that makes perfect sense. I don't think this needs to be further investigated at this stage, if I understand correctly what happened:

   1. A user started uploading a file to the web app.
   2. As the file was being processed, detections were being loaded into the db. 
   3. An error was encountered by the web app at some stage in the file (or in most cases as demonstrated above this might have been a network issue), therefore an error status was assigned to the ID of the uploaded file.
   4. A similar file is likely to have been re-uploaded later on with the error fixed, or when there was no network issue.
