### ISSUE TITLE
Simultaneous chronological deployment/recovery issues 

### ISSUE THREAD

**Issue by astecken** [aodn/aatams#287]
Fernanda wrote:

Most of the problems that cause the a deployment/recovery to be highlighted come from either,
1.       A deployment time coming before the initialisation time; or
2.       A recovery time coming after the next deployment initialisation time
 
In regards to the example below from the Townsville Reefs project, we have both errors occurring and it is not possible to fix. When you try to fix one of the errors the database either will not change the data, or highlights the other issue.
 
i.e. if you try to fix the issue that the first recovery comes after the second initialisation the database refreshed the recovery screen but does not update the recovery time. If you try to fix the issue that the deployment time of the first deployment comes after the initialisation time the data base gives the error that it can’t carry out that operation because the first and second deployments clash (because of the recovery from the first clashing with the initialisation of the second).
 
So you are stuck in a catch 22 of not being able to fix either error. I know this is quite confusing but as the database stands at present these issues can’t be fixed from the users end.
 
.
2012-11-21T23:09:59+0000	2012-11-21T11:00:48+1000	Lodestone Reef
Lodestone 1
18.69122°S 147.08833°E (datum:WGS 84)	VR2W-111015
		Andrew Tobin	18.69122°S 147.08833°E (datum:WGS 84)	2013-05-15T08:22:36+1000	RECOVERED
.
2013-05-14T22:17:51+0000	2013-05-15T09:20:00+1000	Lodestone Reef
Lodestone 1
18.69122°S 147.08833°E (datum:WGS 84)	VR2W-111015
		Fernanda de Faria	18.69122°S 147.08833°E (datum:WGS 84)	2013-09-25T15:40:36+1000	RECOVERED
 
Xavier suggested:

1. Modifying the recovery time of the first deployment to be for instance 2013-05-13T07:22:36+1000? 
2. Then you should be able to fix the deployment before initialisation issue (1st deployment)
3. Then you can modify the initialisation and deployment times of the second deployment
4. Eventually you fix up the recovery time of the 1st deployment to its correct value.

Fernanda replied:

The idea suggested did not work. The database refreshed the recovery screen but did not update the recovery time. Also, ideally I shouldn’t have to change the date to the 13th because the actual deployment happened on the 15th. If we keep making this smalls changes to fix errors it might cause trouble later on or when searching the data.

**Comment by xhoenner** [comment]
This is the same issue as https://github.com/aodn/aatams/issues/241
