### ISSUE TITLE
Entered tags not available for tag release

### ISSUE THREAD

**Issue by astecken** [aodn/aatams#291]
I tried to enter the following serial numbers for tags:
1060779, 1060784, 1060785, 1060786, 1060788
They do exist in the DB under the NSW DPI CEFT project but for some reason I cannot choose them from the drop down menu under tagging when creating a new tag release.

**Comment by xhoenner** [comment]
I was able to recreate this issue, and am not sure how the drop down menu list gets generated. Can you still add release information to those tags @astecken? If so does it make the whole process more tedious? We need to know these two bits of information to prioritise this bug and understand the impact on users.

**Comment by astecken** [comment]
No, I cannot add any release information. This is what I meant ;) I'll try to explain in more detail:
Go to 'create new tag release', click on 'create tagging'. If I try to copy and paste the serial number into the appropriate field, it won't show up in the drop down menu to choose from (to pre-populate the remaining fields in this section). Is this a bit clearer now?

**Comment by xhoenner** [comment]
Thanks @astecken for those details, I was able to create tagging by manually populating the remaining fields, but do realise that this is really painful and more prone to entry errors.

**Comment by astecken** [comment]
Hi Xavier! Will you be able to fix this bug?

**Comment by xhoenner** [comment]
@smancini, @pblain this needs to become a VIT as @astecken can't do any data entry without the drop-down menu functioning correctly.

**Comment by pblain** [comment]
I'm happy for this to be a VIT, but I'll leave it to @smancini to make the call.  If this becomes a VIT it is likely that @julian1 will pick it up.  The possible impact on this iteration is that the vocab versioning design (that Julian is working on) will not get done this time around.  I guess it comes down to whether or not @astecken can wait a couple of weeks.

**Comment by astecken** [comment]
It would be great to have this issue sorted asap so I can deal with crucial data entry re unregistered rags in the DB. Thanks a lot to make this a VIT!

**Comment by xhoenner** [comment]
> I tried to enter the following serial numbers for tags: 1060779, 1060784, 1060785, 1060786, 1060788

@jkburges I am thinking that this bug is due to the fact that all serial numbers in the above list are for tags with multiple ping codes? For instance serial_number 1060788 corresponds to a unique tag_id (108925426) but multiple transmitter_ids ("A69-1105-215" and "A69-1105-214"). See https://github.com/aodn/aatams/blob/master/web-app/js/addsurgerytoanimalrelease.js

**Comment by jkburges** [comment]
The bit of code that creates the list of tags is this: https://github.com/aodn/aatams/blob/master/grails-app/services/au/org/emii/aatams/CandidateEntitiesService.groovy#L64

So I would start looking there to see if the tags are showing up.

I *doubt* that it's got anything to do with tags having multiple transmitter IDs, but I could be wrong!

**Comment by jkburges** [comment]
Nice avatar btw @xhoenner.

**Comment by xhoenner** [comment]
Thanks @jkburges! I've done some testing @astecken: as @kereid suggested, these tags don't show up in that drop down menu as their status are 'DEPLOYED'. If changed to 'NEW' you should see them in that list. 

Unfortunately, as the tags you've got listed there have multiple ping codes, you won't be able to change their status through the 'Edit Tag' page as it will throw the following error when you leave the `Ping ID Code` field empty: 'Property [pingCode] of class [class au.org.emii.aatams.Sensor] cannot be null'. And if you try and update each individually it won't work either as the overall status will remain 'DEPLOYED'. Oh and don't try to put in a value in the `Ping ID Code` field otherwise you'll end up with a new transmitter id.

**Comment by xhoenner** [comment]
> Nice avatar btw @xhoenner.

Thanks mate, part of the quadriptych I did a couple of years ago for Movember; beware though, this is PG classified material, it may (definitely does actually) contain content that children find confusing or upsetting.

![mo copy](https://cloud.githubusercontent.com/assets/3443821/13909123/dd33dfbc-ef62-11e5-9aea-31590703a23c.jpg)

**Comment by julian1** [comment]
It's not just children that find them confusing or upsetting.

**Comment by astecken** [comment]
Great pictures!

@xhoenner if I send you a spreadsheet with all the serial numbers/tag IDs, would you be able to change them from DEPLOYED to NEW? I am not sure how they can be deployed. When you search for the tag ID code, e.g. A69-1105-196 (serial number 1060779), in the tag release field there are now results found. Hence, these tags can't be deployed. Or am I missing something here?

**Comment by xhoenner** [comment]
I suspect these tags were flagged as deployed when people entered these tags in through the Create Tag page. Send me a list of all the serial numbers you want me to change from deployed to new and I'll take care of that.

**Comment by jkburges** [comment]
This problem could be solved by deriving the a tag's status from whether or not there's an associated release (and the date of the release) rather than relying on users to enter in the status.  This is what is done for receivers.

I thought I had put an issue in for this - can't find it in github - but it may have been in redmine it was that long ago!

**Comment by xhoenner** [comment]
> This problem could be solved by deriving the a tag's status from whether or not there's an associated release (and the date of the release) rather than relying on users to enter in the status.

I agree this seems to be the best option to avoid this kind of errors in the future. How would you deal though with the other possible tag status (*e.g.* recovered, retired, stolen, lost)?

**Comment by jkburges** [comment]
> How would you deal though with the other possible tag status (e.g. recovered, retired, stolen, lost)

First question would be to ask if anyone would actually *need* these statuses for tags (how do you determine that a tag is lost for example, and not just still deployed?) - so it's a bit different from receivers in that respect.

In any case, you could still allow users to override/update a status, but certainly the default should be based on whether there's a release or not, and ordinarily users wouldn't need to worry about setting the status explicitly.

**Comment by xhoenner** [comment]
> First question would be to ask if anyone would actually need these statuses for tags

Here's below a breakdown of the number of registered tags grouped by status.

status | count
------ | -----
DAMAGED | 4
DEPLOYED | 5045
LOST | 31
NEW | 1556
RECOVERED | 230
RETIRED | 1
 | 1907

  > You could still allow users to override/update a status, but certainly the default should be based on whether there's a release or not, and ordinarily users wouldn't need to worry about setting the status explicitly.

Yes, that does sound like the way forward, the status for a given tag ID should be changed automatically to deployed when that tag gets assigned to an animal release in https://aatams.emii.org.au/aatams/animalRelease/create. 
Furthermore, when entering a new tag ID through https://aatams.emii.org.au/aatams/sensor/create, the deployed status shouldn't be available if that tag doesn't have a corresponding release ID.

**Comment by astecken** [comment]
@xhoenner I am sending you a list of the tag SN now so they can be changed from deployed to new. Let me know when you have amended those so I can continue with the data entry :)

As for tag status in general, I think there shouldn't really be any other status than deployed or new, i.e. new when just created and deployed when released. Usually tags stay in an animal for the rest of their lives until the battery runs out. @xhoenner Could you produce a list with any other status (lost, damaged, retired, recovered), pls, so I can contact owners to see what happened with those exactly?

Thanks!

**Comment by xhoenner** [comment]
Thanks @astecken, I'll take care of changing the serial number of those tags, it won't happen before next week though.

Here's below the list you requested.

transmitter_id | serial_number | project_name | status
-------------- | ------------- | ------------ | ------
A69-9001-21544 | 1219879 | MQ Port Jackson shark movements and social networks | RECOVERED
A69-1303-36454 | 1091564 | NSW DPI (Artificial Reef Network) | RECOVERED
A69-9002-8122 | 1145825 | NSW DPI (Artificial Reef Network) | RECOVERED
A69-9002-8123 | 1145825 | NSW DPI (Artificial Reef Network) | RECOVERED
A180-9002-14117 | a69-9002-14777 | NSW DPI Coastal and Estuarine Fish Tracking (CEFT) | RETIRED
A69-1303-37312 | 1092914 | NSW DPI Jervis Bay | DAMAGED
A69-1303-14678 | 1064945 | UQ Project Manta east Australia | LOST
A69-1303-54723 | 1064939 | UQ Project Manta east Australia | LOST
A69-1303-54725 | 1064941 | UQ Project Manta east Australia | LOST
A69-1303-64938 | 1083958 | UQ Project Manta east Australia | LOST
A69-1303-64939 | 1083959 | UQ Project Manta east Australia | LOST
A69-1601-30999 | 1130011 | UQ Project Manta east Australia | LOST
A69-1601-31000 | 1130012 | UQ Project Manta east Australia | LOST
A69-1601-32249 | 1116618 | UQ Project Manta east Australia | LOST
A69-1601-32250 | 1116619 | UQ Project Manta east Australia | LOST
A69-1601-32251 | 1116620 | UQ Project Manta east Australia | LOST
A69-1601-32253 | 1116622 | UQ Project Manta east Australia | LOST
A69-1601-32254 | 1116623 | UQ Project Manta east Australia | LOST
A69-1601-32255 | 1116624 | UQ Project Manta east Australia | LOST
A69-1601-32256 | 1116625 | UQ Project Manta east Australia | LOST
A69-1601-32257 | 1116626 | UQ Project Manta east Australia | LOST
A69-1601-32258 | 1116627 | UQ Project Manta east Australia | LOST
A69-1601-32692 | 1104219 | UQ Project Manta east Australia | LOST
A69-1601-32694 | 1104221 | UQ Project Manta east Australia | LOST
A69-1601-32695 | 1104222 | UQ Project Manta east Australia | LOST

**Comment by astecken** [comment]
@xhoenner I contacted the owners and will get back to you once I hear from them.

**Comment by xhoenner** [comment]
@astecken the status of all the tags in the list you sent me has now been changed to NEW so you should be able to proceed with the data entry.

**Comment by astecken** [comment]
Will do. Thanks!

**Comment by xhoenner** [comment]
Any progress on that front @astecken?

**Comment by astecken** [comment]
@xhoenner I have heard from some researchers and just followed up again on the remaining ones ;) I'll keep you posted.

**Comment by xhoenner** [comment]
Any progress on this issue @astecken?

**Comment by astecken** [comment]
It looks like that the remaining tag IDs with status recovered, retired, damaged, and lost are actually correct. There are several explanations from different researchers, e.g.  when lost, animals (manta rays) with external tags were resighted but didn't have any tags attached anymore, recovered means when a tag was returned by fishermen but not reused (yet).
@xhoenner I think we can close this issue too.
