### ISSUE TITLE
Erroneous release location

### ISSUE THREAD

**Issue by xhoenner** [aodn/aatams#294]
@astecken here's below a list of 284 animal releases having erroneous release or capture lat/lon coordinates. I believe most of them are due to the fact that people put in latitude North instead of South when releasing their tags so I could easily change the latitude sign to minus (North used to be the default in the web app). Could you have a look at that list and advise what needs to be done?

transmitter_id | tag_id | project_name | longitude | latitude
-------------- | ------ | ------------ | --------- | --------
A69-9002-8459 | 77523615 | AATAMS One Tree Island | 152.0869 | 23.5048
A69-9002-8460 | 77523605 | AATAMS One Tree Island | 152.08459 | 23.48841
A69-9002-8461 | 77523595 | AATAMS One Tree Island | 152.08459 | 23.48841
A69-9002-8462 | 77523531 | AATAMS One Tree Island | 152.08459 | 23.48841
A69-9002-8463 | 77523521 | AATAMS One Tree Island | 152.07964 | 23.50058
A69-9002-8464 | 77523511 | AATAMS One Tree Island | 152.07945 | 23.50208
A69-9002-8465 | 77523501 | AATAMS One Tree Island | 152.08118 | 23.5018
A69-9002-8466 | 77523451 | AATAMS One Tree Island | 152.08662 | 23.50498
A69-9002-8467 | 77523461 | AATAMS One Tree Island | 152.08662 | 23.50498
A69-9002-8468 | 77523471 | AATAMS One Tree Island | 152.08662 | 23.50498
A69-9002-8469 | 77523481 | AATAMS One Tree Island | 152.08824 | 23.50356
A69-9002-8470 | 77523491 | AATAMS One Tree Island | 152.08119 | 23.50179
A69-9002-8471 | 77523441 | AATAMS One Tree Island | 152.08823 | 23.50481
A69-9002-8472 | 77523431 | AATAMS One Tree Island | 152.07631 | 23.48779
A69-9002-8473 | 77523421 | AATAMS One Tree Island | 152.08751 | 23.50752
A69-1303-154 | 19983397 | Bluefin tuna WA | 118.8166667 | -39.66666667
A69-1303-8509 | 19980271 | CSIRO: Animal Tagging | 122.0006 | -40.0357
A69-1601-22870 | 129371752 | Diadromous fish movements in the O'Connell R, central Qld | 148.60283 | -70.75311
A69-1303-44664 | 43603465 | JCU Cleveland Bay | 146.88358 | 19.25252
A69-1303-44665 | 43603476 | JCU Cleveland Bay | 146.87885 | 19.27635
A69-1303-44666 | 43603487 | JCU Cleveland Bay | 146.8696 | 19.27006
A69-1303-44667 | 43603498 | JCU Cleveland Bay | 146.8696 | 19.27006
A69-1303-44668 | 43603509 | JCU Cleveland Bay | 146.8696 | 19.27006
A69-1303-44669 | 43603520 | JCU Cleveland Bay | 146.8696 | 19.27006
A69-1303-44670 | 43603531 | JCU Cleveland Bay | 146.88464 | 19.29288
A69-1303-44671 | 43603542 | JCU Cleveland Bay | 146.88464 | 19.29288
A69-1303-44673 | 43603581 | JCU Cleveland Bay | 146.88952 | 19.27334
A69-1303-44674 | 43603616 | JCU Cleveland Bay | 146.96264 | 19.27059
A69-1303-44675 | 43603647 | JCU Cleveland Bay | 146.87321 | 19.28127
A69-1303-44676 | 43603670 | JCU Cleveland Bay | 146.89474 | 19.28018
A69-1303-44680 | 43603716 | JCU Cleveland Bay | 146.96264 | 19.27059
A69-1303-44681 | 43603727 | JCU Cleveland Bay | 146.99244 | 19.23458
A69-1303-44683 | 43603738 | JCU Cleveland Bay | 146.89645 | 19.29197
A69-1303-44684 | 43603749 | JCU Cleveland Bay | 146.95994 | 19.26574
A69-1303-44685 | 43603780 | JCU Cleveland Bay | 146.88425 | 19.2912
A69-1303-44686 | 43603803 | JCU Cleveland Bay | 146.89053 | 19.27349
A69-1303-44687 | 43603830 | JCU Cleveland Bay | 146.87321 | 19.28127
A69-1303-44688 | 43603847 | JCU Cleveland Bay | 146.87321 | 19.28127
A69-1303-44689 | 43603870 | JCU Cleveland Bay | 146.92943 | 19.29305
A69-1303-44690 | 43603889 | JCU Cleveland Bay | 146.92878 | 19.29317
A69-1303-44691 | 43603922 | JCU Cleveland Bay | 146.96355 | 19.22501
A69-1303-44692 | 43603956 | JCU Cleveland Bay | 146.94672 | 19.237
A69-1303-44693 | 43603945 | JCU Cleveland Bay | 146.0039 | 19.227
A69-1303-44694 | 43603967 | JCU Cleveland Bay | 146.0039 | 19.227
A69-1303-44695 | 43603978 | JCU Cleveland Bay | 146.96817 | 19.25867
A69-1303-44696 | 43603989 | JCU Cleveland Bay | 146.93128 | 19.26742
A69-1303-44697 | 43604000 | JCU Cleveland Bay | 146.92878 | 19.29317
A69-1303-44698 | 43604011 | JCU Cleveland Bay | 146.94672 | 19.237
A69-1303-44709 | 43604034 | JCU Cleveland Bay | 146.88389 | 19.29318
A69-1303-46979 | 43604052 | JCU Cleveland Bay | 146.88741 | 19.29955
A69-1303-46980 | 43604073 | JCU Cleveland Bay | 146.88952 | 19.27334
A69-1303-46982 | 43604094 | JCU Cleveland Bay | 146.88603 | 19.29261
A69-1303-46983 | 43604115 | JCU Cleveland Bay | 146.88321 | 19.29209
A69-1303-46984 | 43604136 | JCU Cleveland Bay | 146.88276 | 19.29895
A69-1303-46985 | 43604179 | JCU Cleveland Bay | 146.88603 | 19.29261
A69-1303-46987 | 43604190 | JCU Cleveland Bay | 146.88603 | 19.29261
A69-1303-46988 | 43604201 | JCU Cleveland Bay | 146.88603 | 19.29261
A69-1303-46989 | 43604212 | JCU Cleveland Bay | 146.88389 | 19.29318
A69-1303-46990 | 43604223 | JCU Cleveland Bay | 146.88389 | 19.29318
A69-1303-46992 | 43604234 | JCU Cleveland Bay | 146.96264 | 19.27059
A69-1303-46994 | 43604245 | JCU Cleveland Bay | 146.88603 | 19.29261
A69-1303-46996 | 43604256 | JCU Cleveland Bay | 146.88741 | 19.29955
A69-1303-46997 | 43604267 | JCU Cleveland Bay | 146.88321 | 19.29209
A69-1303-47002 | 43649980 | JCU Cleveland Bay | 146.99558 | 19.24192
A69-1303-56549 | 43109810 | JCU Cleveland Bay | 14.97482 | -19.28239
A69-1303-63542 | 43649991 | JCU Cleveland Bay | 146.89343 | 19.29409
A69-1303-63544 | 43650002 | JCU Cleveland Bay | 146.95739 | 19.27826
A69-1303-63545 | 43650013 | JCU Cleveland Bay | 146.93731 | 19.28877
A69-1303-63546 | 43650024 | JCU Cleveland Bay | 146.85986 | 19.23926
A69-1303-63547 | 43650035 | JCU Cleveland Bay | 146.90495 | 19.29676
A69-1303-63549 | 43650046 | JCU Cleveland Bay | 146.88649 | 19.25767
A69-1303-63550 | 43650057 | JCU Cleveland Bay | 146.99566 | 19.23575
A69-1303-63551 | 43650068 | JCU Cleveland Bay | 146.992 | 19.2427
A69-1303-63552 | 43650081 | JCU Cleveland Bay | 146.99341 | 19.24987
A69-1303-63553 | 43651192 | JCU Cleveland Bay | 146.79156 | 19.16043
A69-1303-63557 | 43651203 | JCU Cleveland Bay | 146.88649 | 19.25767
A69-1303-63629 | 43651214 | JCU Cleveland Bay | 146.88763 | 19.27908
A69-1303-63632 | 43651223 | JCU Cleveland Bay | 146.88425 | 19.2912
A69-1303-63633 | 43651234 | JCU Cleveland Bay | 146.99551 | 19.23606
A69-1303-63637 | 43651245 | JCU Cleveland Bay | 146.88464 | 19.29288
A69-1601-32027 | 43603082 | JCU Cleveland Bay | 146.887625 | 19.27908
A69-1601-32028 | 43603110 | JCU Cleveland Bay | 146.9439 | 19.27515
A69-1601-32029 | 43603121 | JCU Cleveland Bay | 146.87625 | 19.27819
A69-1601-32031 | 43603155 | JCU Cleveland Bay | 146.87625 | 19.27819
A69-1601-32032 | 43603138 | JCU Cleveland Bay | 146.87625 | 19.27819
A69-1601-32032 | 43603166 | JCU Cleveland Bay | 146.87625 | 19.27819
A69-1601-32033 | 43603177 | JCU Cleveland Bay | 147.01693 | 19.19532
A69-1601-32034 | 43603188 | JCU Cleveland Bay | 147.01693 | 19.19532
A69-1601-32035 | 43603093 | JCU Cleveland Bay | 146.88763 | 19.27908
A69-1601-32036 | 43603199 | JCU Cleveland Bay | 146.92807 | 19.2772
A69-1601-32037 | 43603210 | JCU Cleveland Bay | 146.88603 | 19.29261
A69-1601-32038 | 43603221 | JCU Cleveland Bay | 147.01625 | 19.20033
A69-1601-32039 | 43603238 | JCU Cleveland Bay | 146.87461 | 19.28207
A69-1601-32040 | 43603249 | JCU Cleveland Bay | 146.88952 | 19.27334
A69-1601-32043 | 43603260 | JCU Cleveland Bay | 146.88952 | 19.27334
A69-1601-32044 | 43603288 | JCU Cleveland Bay | 146.88837 | 19.28496
A69-1601-32760 | 43603378 | JCU Cleveland Bay | 146.87885 | 19.27635
A69-1601-32761 | 43603399 | JCU Cleveland Bay | 146.96557 | 19.27908
A69-1601-32762 | 43603410 | JCU Cleveland Bay | 146.88763 | 19.27908
A69-1601-32763 | 43603421 | JCU Cleveland Bay | 146.88425 | 19.2912
A69-1601-32764 | 43603432 | JCU Cleveland Bay | 146.8696 | 19.27006
A69-1601-32766 | 43603443 | JCU Cleveland Bay | 146.88425 | 19.2912
A69-1601-32767 | 43603454 | JCU Cleveland Bay | 146.8696 | 19.27006
A69-1601-44701 | 43604022 | JCU Cleveland Bay | 146.97466 | 19.27749
A69-1601-36747 | 129187098 | Lane Cove River Australian Bass | 151.144917 | -3.784611
A69-9001-21551 | 128331659 | MQ Port Jackson shark movements and social networks | 151.276475 | 33.8006722222222
A69-1105-10 | 38784066 | Mud Crab Tracking Logan River | 153.292297 | 27.693081
A69-1105-9 | 38784066 | Mud Crab Tracking Logan River | 153.292297 | 27.693081
A69-1105-9 | 38784066 | Mud Crab Tracking Logan River | 153.292297 | 27.693081
A69-1601-4517 | 38784130 | Mud Crab Tracking Logan River | 153.247589 | 27.697281
A69-1601-4519 | 38784176 | Mud Crab Tracking Logan River | 153.239441 | 27.686163
A69-1601-4519 | 38784176 | Mud Crab Tracking Logan River | 153.239441 | 27.686163
A69-1601-4520 | 38784008 | Mud Crab Tracking Logan River | 153.239441 | 27.686163
A69-1601-4521 | 38784019 | Mud Crab Tracking Logan River | 153.235566 | 27.684661
A69-1601-4521 | 38784019 | Mud Crab Tracking Logan River | 153.247116 | 27.697355
A69-1601-4522 | 38784097 | Mud Crab Tracking Logan River | 153.243515 | 27.693548
A69-1601-4523 | 38784141 | Mud Crab Tracking Logan River | 153.261139 | 27.693867
A69-1601-4527 | 38784030 | Mud Crab Tracking Logan River | 153.292099 | 27.693111
A69-1601-4533 | 38784152 | Mud Crab Tracking Logan River | 153.261139 | 27.693867
A69-1601-4535 | 38784119 | Mud Crab Tracking Logan River | 153.272537 | 27.697939
A69-1601-4536 | 38784086 | Mud Crab Tracking Logan River | 153.242355 | 27.694582
A69-1601-11757 | 96631169 | NSW DPI (Artificial Reef Network) | 151.28871 | 33.85298
A69-9002-8146 | 96631159 | NSW DPI (Artificial Reef Network) | 151.28871 | 33.85298
A69-9002-8147 | 96631159 | NSW DPI (Artificial Reef Network) | 151.28871 | 33.85298
A69-9002-8760 | 110411580 | NSW DPI (Artificial Reef Network) | 151.29883 | 33.873917
A69-1303-52869 | 129560398 | NSW DPI Coastal and Estuarine Fish Tracking (CEFT) | 150.71324 | 34.89006
A69-9001-31935 | 71373793 | NSW DPI Movements of Coastal Sharks | 151.24509 | 33.86166
A69-9002-14675 | 71373806 | NSW DPI Movements of Coastal Sharks | 151.24509 | 0
A69-9002-14675 | 71373806 | NSW DPI Movements of Coastal Sharks | 151.24509 | 0
A69-9002-14676 | 71373806 | NSW DPI Movements of Coastal Sharks | 151.24509 | 0
A69-9002-14676 | 71373806 | NSW DPI Movements of Coastal Sharks | 151.24509 | 0
A69-9002-14689 | 71373811 | NSW DPI Movements of Coastal Sharks | 151.24509 | 33.86166
A69-9002-14689 | 71373811 | NSW DPI Movements of Coastal Sharks | 151.24509 | 33.86166
A69-9002-14690 | 71373811 | NSW DPI Movements of Coastal Sharks | 151.24509 | 33.86166
A69-9002-14690 | 71373811 | NSW DPI Movements of Coastal Sharks | 151.24509 | 33.86166
A69-1601-28315 | 81653016 | Obi Obi Creek fish and turtle tracking project | 152.7642 | 26.619
A69-1601-28323 | 81653020 | Obi Obi Creek fish and turtle tracking project | 152.7642 | 26.619
A69-1601-29385 | 81653060 | Obi Obi Creek fish and turtle tracking project | 152.8291 | 26.6534
A69-1601-29393 | 81653056 | Obi Obi Creek fish and turtle tracking project | 152.7948 | 26.6459
A69-1601-29401 | 81653032 | Obi Obi Creek fish and turtle tracking project | 152.8139 | 26.6491
A69-1601-29403 | 81653048 | Obi Obi Creek fish and turtle tracking project | 152.78221 | 26.63067
A69-1601-29405 | 81653044 | Obi Obi Creek fish and turtle tracking project | 152.7948 | 26.6459
A69-1601-29406 | 81653040 | Obi Obi Creek fish and turtle tracking project | 152.7642 | 26.619
A69-1601-29407 | 81653028 | Obi Obi Creek fish and turtle tracking project | 152.8139 | 26.6491
A69-1601-29408 | 81653036 | Obi Obi Creek fish and turtle tracking project | 152.7948 | 26.6459
A69-1601-29410 | 81652988 | Obi Obi Creek fish and turtle tracking project | 152.93 | 26.38018
A69-1601-29411 | 81652996 | Obi Obi Creek fish and turtle tracking project | 152.8139 | 26.6491
A69-1601-29412 | 81653008 | Obi Obi Creek fish and turtle tracking project | 152.8139 | 26.6491
A69-1601-29413 | 81652992 | Obi Obi Creek fish and turtle tracking project | 152.6274 | 26.4904
A69-1601-29414 | 81653012 | Obi Obi Creek fish and turtle tracking project | 152.8139 | 26.6491
A69-9002-6483 | 81653024 | Obi Obi Creek fish and turtle tracking project | 152.8139 | 26.6491
A69-9002-4018 | 41099264 | Redthroat emperor movement (Capricorn-Bunkers) | 152.06 | 23.4881
A69-9002-4018 | 41099264 | Redthroat emperor movement (Capricorn-Bunkers) | 152.06 | 23.4881
A69-9002-4019 | 41102494 | Redthroat emperor movement (Capricorn-Bunkers) | 152.06 | 23.4881
A69-9002-4019 | 41102494 | Redthroat emperor movement (Capricorn-Bunkers) | 152.06 | 23.4881
A69-9002-4020 | 41103772 | Redthroat emperor movement (Capricorn-Bunkers) | 151.92799 | 23.43324
A69-9002-4020 | 41103772 | Redthroat emperor movement (Capricorn-Bunkers) | 151.92799 | 23.43324
A69-9002-4021 | 41105276 | Redthroat emperor movement (Capricorn-Bunkers) | 151.92255 | 23.43379
A69-9002-4021 | 41105276 | Redthroat emperor movement (Capricorn-Bunkers) | 151.92255 | 23.43379
A69-9002-4022 | 41106780 | Redthroat emperor movement (Capricorn-Bunkers) | 151.91161 | 23.44693
A69-9002-4022 | 41106780 | Redthroat emperor movement (Capricorn-Bunkers) | 151.91161 | 23.44693
A69-9002-4023 | 41120784 | Redthroat emperor movement (Capricorn-Bunkers) | 151.91348 | 23.44822
A69-9002-4024 | 41174813 | Redthroat emperor movement (Capricorn-Bunkers) | 151.91348 | 23.44822
A69-9002-4024 | 41174813 | Redthroat emperor movement (Capricorn-Bunkers) | 151.91348 | 23.44822
A69-9002-4025 | 41177317 | Redthroat emperor movement (Capricorn-Bunkers) | 151.91348 | 23.44822
A69-9002-4025 | 41177317 | Redthroat emperor movement (Capricorn-Bunkers) | 151.91348 | 23.44822
A69-9002-4026 | 41181240 | Redthroat emperor movement (Capricorn-Bunkers) | 151.94952 | 23.43065
A69-9002-4027 | 41188831 | Redthroat emperor movement (Capricorn-Bunkers) | 151.92108 | 23.4534
A69-9002-4028 | 41192335 | Redthroat emperor movement (Capricorn-Bunkers) | 151.94919 | 23.43069
A69-9002-4029 | 41195839 | Redthroat emperor movement (Capricorn-Bunkers) | 151.94919 | 23.43069
A69-9002-4030 | 41197843 | Redthroat emperor movement (Capricorn-Bunkers) | 151.94919 | 23.43069
A69-9002-4031 | 41201847 | Redthroat emperor movement (Capricorn-Bunkers) | 151.92294 | 23.43363
A69-9002-4032 | 41217851 | Redthroat emperor movement (Capricorn-Bunkers) | 151.90405 | 23.43596
A69-9002-4033 | 41221355 | Redthroat emperor movement (Capricorn-Bunkers) | 151.93285 | 23.46361
A69-9002-4034 | 41223359 | Redthroat emperor movement (Capricorn-Bunkers) | 151.93285 | 23.46361
A69-9002-7029 | 42948407 | Redthroat emperor movement (Capricorn-Bunkers) | 151.94939 | 23.47136
A69-9002-7030 | 42948411 | Redthroat emperor movement (Capricorn-Bunkers) | 151.91962 | 23.45233
A69-9002-7031 | 42948415 | Redthroat emperor movement (Capricorn-Bunkers) | 151.91962 | 23.45233
A69-9002-7032 | 42948429 | Redthroat emperor movement (Capricorn-Bunkers) | 151.91962 | 23.45233
A69-9002-7033 | 42948419 | Redthroat emperor movement (Capricorn-Bunkers) | 151.91962 | 23.45233
A69-9002-7033 | 42948419 | Redthroat emperor movement (Capricorn-Bunkers) | 151.91962 | 23.45233
A69-9002-7034 | 42948433 | Redthroat emperor movement (Capricorn-Bunkers) | 151.91962 | 23.45233
A69-9002-7035 | 42948437 | Redthroat emperor movement (Capricorn-Bunkers) | 151.94939 | 23.47136
A69-9002-7036 | 42948441 | Redthroat emperor movement (Capricorn-Bunkers) | 151.92267 | 23.45469
A69-9002-7037 | 42948445 | Redthroat emperor movement (Capricorn-Bunkers) | 151.92267 | 23.45469
A69-9002-7038 | 42948449 | Redthroat emperor movement (Capricorn-Bunkers) | 151.9122 | 23.44742
A69-9002-7039 | 42948453 | Redthroat emperor movement (Capricorn-Bunkers) | 151.9122 | 23.44742
A69-9002-7040 | 42948457 | Redthroat emperor movement (Capricorn-Bunkers) | 151.9122 | 23.44742
A69-9002-7041 | 42948461 | Redthroat emperor movement (Capricorn-Bunkers) | 151.94142 | 23.43465
A69-9002-7042 | 42948465 | Redthroat emperor movement (Capricorn-Bunkers) | 151.92082 | 23.43358
A69-9002-7043 | 42948469 | Redthroat emperor movement (Capricorn-Bunkers) | 151.92082 | 23.43358
A69-9002-7044 | 42948473 | Redthroat emperor movement (Capricorn-Bunkers) | 151.92082 | 23.43358
A69-9002-7045 | 42948477 | Redthroat emperor movement (Capricorn-Bunkers) | 151.91173 | 23.43403
A69-9002-7046 | 42948481 | Redthroat emperor movement (Capricorn-Bunkers) | 151.91577 | 23.43389
A69-9002-7047 | 42948485 | Redthroat emperor movement (Capricorn-Bunkers) | 151.91577 | 23.43389
A69-9002-7048 | 42948489 | Redthroat emperor movement (Capricorn-Bunkers) | 151.91577 | 23.43389
A69-9002-13772 | 51060883 | Townsville Reefs | 147.28714 | 18.62234
A69-9002-13773 | 63356846 | Townsville Reefs | 147.52162 | 18.80292
A69-9002-13774 | 63356857 | Townsville Reefs | 147.52162 | 18.80292
A69-9002-13775 | 63356868 | Townsville Reefs | 147.52162 | 18.80292
A69-9002-13776 | 63356879 | Townsville Reefs | 147.52162 | 18.80292
A69-9002-13777 | 63356890 | Townsville Reefs | 147.52162 | 18.80292
A69-9002-13777 | 63356890 | Townsville Reefs | 147.52162 | 18.80292
A69-9002-13778 | 63356914 | Townsville Reefs | 147.52162 | 18.80292
A69-9002-13779 | 63356925 | Townsville Reefs | 147.52162 | 18.80292
A69-9002-13780 | 63356936 | Townsville Reefs | 147.52162 | 18.80292
A69-9002-13781 | 63356947 | Townsville Reefs | 147.52162 | 18.80292
A69-9002-13782 | 63356958 | Townsville Reefs | 147.52267 | 18.79128
A69-9002-13783 | 63356969 | Townsville Reefs | 147.52267 | 18.79128
A69-9002-13784 | 63356980 | Townsville Reefs | 147.52267 | 18.79128
A69-9002-13785 | 63357003 | Townsville Reefs | 147.52267 | 18.79128
A69-9002-13786 | 63357014 | Townsville Reefs | 147.52258 | 18.80432
A69-9002-13788 | 63357034 | Townsville Reefs | 147.52258 | 18.80432
A69-9002-13789 | 63357043 | Townsville Reefs | 147.51912 | 18.79872
A69-9002-13792 | 63357076 | Townsville Reefs | 147.0974 | 18.68595
A69-9002-13793 | 63357095 | Townsville Reefs | 147.09398 | 18.68702
A69-9002-13797 | 69918509 | Townsville Reefs | 147.26433 | 18.73813
A69-9002-13798 | 69918520 | Townsville Reefs | 147.2625 | 18.74186
A69-9002-13799 | 69918530 | Townsville Reefs | 147.08475 | 18.69103
A69-9002-13800 | 69918541 | Townsville Reefs | 147.29202 | 18.62198
A69-9002-13808 | 69918697 | Townsville Reefs | 146.6586 | 18.38492
A69-9002-13808 | 69918697 | Townsville Reefs | 146.6586 | 18.38492
A69-9002-13811 | 77523203 | Townsville Reefs | 147.29674 | 18.63164
A69-9002-13816 | 80747059 | Townsville Reefs | 147.38626 | 18.51749
A69-9002-13817 | 80747070 | Townsville Reefs | 147.38626 | 18.51749
A69-9002-13821 | 80747114 | Townsville Reefs | 147.08661 | 18.69208
A69-9002-13822 | 93016168 | Townsville Reefs | 147.30258 | 18.62164
A69-9002-13822 | 93016168 | Townsville Reefs | 147.30258 | 18.62164
A69-9002-13823 | 69918706 | Townsville Reefs | 147.08464 | 18.69131
A69-9002-13823 | 69918706 | Townsville Reefs | 147.08464 | 18.69131
A69-9002-13826 | 93016188 | Townsville Reefs | 147.09047 | 18.69937
A69-9002-13828 | 93016210 | Townsville Reefs | 147.25739 | 18.75861
A69-9002-13829 | 93016221 | Townsville Reefs | 147.25739 | 18.75861
A69-9002-13830 | 93016233 | Townsville Reefs | 147.25739 | 18.75861
A69-9002-14773 | 43669564 | Townsville Reefs | 147.16795 | 18.92943
A69-9002-14773 | 43669564 | Townsville Reefs | 147.16795 | 18.92943
A69-9002-14774 | 43669568 | Townsville Reefs | 147.16846 | 18.93067
A69-9002-14774 | 43669568 | Townsville Reefs | 147.16846 | 18.93067
A69-9002-14776 | 43669576 | Townsville Reefs | -147.0153 | -18.63291
A69-9002-14776 | 43669576 | Townsville Reefs | -147.0153 | -18.63291
A69-9002-14778 | 43669584 | Townsville Reefs | 147.29243 | 18.62105
A69-9002-14778 | 43669584 | Townsville Reefs | 147.29243 | 18.62105
A69-9002-14779 | 43669588 | Townsville Reefs | 146.8681 | 18.47792
A69-9002-14779 | 43669588 | Townsville Reefs | 146.8681 | 18.47792
A69-9002-14780 | 43669592 | Townsville Reefs | 147.2523833 | 18.74445
A69-9002-14780 | 43669592 | Townsville Reefs | 147.2523833 | 18.74445
A69-9002-14782 | 43669600 | Townsville Reefs | 147.39352 | 18.52406
A69-9002-14782 | 43669600 | Townsville Reefs | 147.39352 | 18.52406
A69-9002-14783 | 43669604 | Townsville Reefs | 146.86656 | 18.46708
A69-9002-14783 | 43669604 | Townsville Reefs | 146.86656 | 18.46708
A69-9002-14786 | 43669616 | Townsville Reefs | 146.86595 | 18.46554
A69-9002-14786 | 43669616 | Townsville Reefs | 146.86595 | 18.46554
A69-9002-14787 | 43669620 | Townsville Reefs | 146.86432 | 18.47613
A69-9002-14787 | 43669620 | Townsville Reefs | 146.86432 | 18.47613
A69-9002-14788 | 43669624 | Townsville Reefs | 147.10219 | 18.68387
A69-9002-14788 | 43669624 | Townsville Reefs | 147.10219 | 18.68387
A69-9002-14789 | 43669628 | Townsville Reefs | 147.86432 | 18.47613
A69-9002-14789 | 43669628 | Townsville Reefs | 147.86432 | 18.47613
A69-9002-14790 | 43669632 | Townsville Reefs | 147.30127 | 18.61987
A69-9002-14790 | 43669632 | Townsville Reefs | 147.30127 | 18.61987
A69-9002-14791 | 43669636 | Townsville Reefs | 147.30098 | 18.62009
A69-9002-14791 | 43669636 | Townsville Reefs | 147.30098 | 18.62009
A69-9002-14792 | 43669640 | Townsville Reefs | 147.30098 | 18.62009
A69-9002-14792 | 43669640 | Townsville Reefs | 147.30098 | 18.62009
A69-9002-14813 | 51060865 | Townsville Reefs | 147.3003 | 18.62234
A69-9002-14816 | 69918487 | Townsville Reefs | 147.51837 | 18.9216
A69-9002-7014 | 56771594 | Townsville Reefs | 147.08821 | 18.69052
A69-9002-7014 | 56771594 | Townsville Reefs | 147.08821 | 18.69052
A69-9002-8414 | 94997792 | Townsville Reefs | 147.256 | 18.7442
A69-9002-8447 | 60431380 | Townsville Reefs | 147.09596 | 18.68509
A69-9002-8447 | 60431380 | Townsville Reefs | 147.09596 | 18.68509
A69-9002-8448 | 60431384 | Townsville Reefs | 147.09596 | 18.68509
A69-9002-8449 | 60431388 | Townsville Reefs | 147.0847 | 18.69062
A69-1601-18742 | 128192310 | UQ grey nurse shark project | 153.192367 | 25.926883
A69-1601-18744 | 128192318 | UQ grey nurse shark project | 153.192367 | 25.926883
A69-1601-18745 | 128192321 | UQ grey nurse shark project | 153.192367 | 25.926883
A69-1601-18746 | 128192325 | UQ grey nurse shark project | 153.192367 | 25.926883
A69-1303-121 | 38938086 | Wenlock River Array, Gulf of Carpentaria | 142.01555 | 12.2682
A69-1303-121 | 38938086 | Wenlock River Array, Gulf of Carpentaria | 142.01555 | 12.2682
A69-1303-122 | 38938046 | Wenlock River Array, Gulf of Carpentaria | 142.07257 | 12.27561
A69-1303-123 | 38938046 | Wenlock River Array, Gulf of Carpentaria | 142.07257 | 12.27561
A69-1303-13885 | 38938086 | Wenlock River Array, Gulf of Carpentaria | 142.01555 | 12.2682
A69-1303-13885 | 38938086 | Wenlock River Array, Gulf of Carpentaria | 142.01555 | 12.2682
A69-1303-13886 | 38938046 | Wenlock River Array, Gulf of Carpentaria | 142.07257 | 12.27561

For future references, the SQL used to generate that list:
```sql
WITH a AS (
SELECT se.transmitter_id, se.tag_id, p.name AS project_name,
CASE WHEN ar.capturedatetime_timestamp IS NULL THEN ar.releasedatetime_timestamp ELSE ar.capturedatetime_timestamp END AS release_timestamp,
ST_SETSRID(CASE WHEN ar.capture_location IS NULL THEN ar.release_location ELSE ar.capture_location END,4326) AS geom
FROM aatams.animal_release ar
JOIN aatams.surgery su ON ar.id = su.release_id
JOIN aatams.sensor se ON se.tag_id = su.tag_id
JOIN aatams.project p ON p.id = ar.project_id
WHERE ar.capture_location IS NOT NULL OR ar.release_location IS NOT NULL),
b as (
SELECT a.transmitter_id, a.tag_id, a.project_name, ST_X(((ST_DUMP(geom)).geom)) AS longitude, ST_Y(((ST_DUMP(geom)).geom)) AS latitude,
	 CASE WHEN ST_CONTAINS(ST_Polygon(ST_GeomFromText('LINESTRING(129.01 -16.26,129.01  -10.19,137.8 -10.19, 137.8 -16.26,129.01 -16.26)'), 4326),geom) = TRUE THEN 'NT' 
 WHEN ST_CONTAINS(ST_Polygon(ST_GeomFromText('LINESTRING(141 -39.2,141 -36,150.25 -36, 150.25 -39.2,141 -39.2)'), 4326),geom) = TRUE THEN 'Vic' 
  WHEN ST_CONTAINS(ST_Polygon(ST_GeomFromText('LINESTRING(109.8 -35.9,109.8 -10.19,129.01 -10.19, 129.01 -35.9,109.8 -35.9)'), 4326),geom) = TRUE THEN 'WA' 
   WHEN ST_CONTAINS(ST_Polygon(ST_GeomFromText('LINESTRING(137.8 -28.15,137.8 -10.19,155.53 -10.19, 155.53 -28.15,137.8 -28.15)'), 4326),geom) = TRUE THEN 'QLD' 
    WHEN ST_CONTAINS(ST_Polygon(ST_GeomFromText('LINESTRING(149.25 -37.5,149.25 -28.15,155.53 -28.15, 155.53 -37.5,149.25 -37.5)'), 4326),geom) = TRUE THEN 'NSW' 
     WHEN ST_CONTAINS(ST_Polygon(ST_GeomFromText('LINESTRING(141 -44.5,141 -39.2,149.1 -39.2, 149.1 -44.5,141 -44.5)'), 4326),geom) = TRUE THEN 'TAS' 
     WHEN ST_CONTAINS(ST_Polygon(ST_GeomFromText('LINESTRING(129.01 -39.07,129.01 -31.7,141 -31.7, 141 -39.07,129.01 -39.07)'), 4326),geom) = TRUE THEN 'SA'
     WHEN ST_CONTAINS(ST_Polygon(ST_GeomFromText('LINESTRING(171.01 -33.3,179.85 -34.35,179.85 -51.7, 152 -51.7,171.01 -33.3)'), 4326),geom) = TRUE THEN 'NZ' END AS australian_state
FROM a)
SELECT transmitter_id, tag_id, project_name, longitude, latitude
FROM b
WHERE australian_state IS NULL
ORDER BY project_name, transmitter_id, tag_id;
```

**Comment by astecken** [comment]
I changed a few entries and some (the WA Tuna and CSIRO ones) should be correct. All others can be  changed from N to S, pls. I will send you an excel spreadsheet with detailed comments by email now.

**Comment by xhoenner** [comment]
Great, thanks @astecken, the only remaining tag to change is A69-1303-56549 which has a longitude of 14. instead of 146.

**Comment by astecken** [comment]
I changed this one too now ans it should all be cleaned up.

**Comment by xhoenner** [comment]
Thanks @astecken, I'll fix up the other ones and will get another extract from the db then.

**Comment by astecken** [comment]
Are those all sorted now?

**Comment by xhoenner** [comment]
not yet no

**Comment by xhoenner** [comment]
Only six left now. The longitude of the 3rd record is definitely wrong, can you update this record in the web app @astecken? If you're happy with the other records, I'll close this issue.

transmitter_id | tag_id | project_name | longitude | latitude
-------------- | ------ | ------------ | --------- | --------
A69-1303-154 | 19983397 | Bluefin tuna WA | 118.8166667 | -39.66666667
A69-1303-8509 | 19980271 | CSIRO: Animal Tagging | 122.0006 | -40.0357
A69-9001-30972 | 129583849 | FRDC WA commercial sharks | 19.786417 | -19.786417
A69-1303-64953 | 4462719 | QLD Large Shark Tagging Program | 155.856065 | -19.391955
A69-1303-64957 | 4462716 | QLD Large Shark Tagging Program | 155.856065 | -19.391955
A69-1303-64962 | 4462739 | QLD Large Shark Tagging Program | 165.603529 | -20.918754

**Comment by astecken** [comment]
@xhoenner Changed the 3rd entry but all others are correct. You can now change the script if you like :) Thanks!
