### ISSUE TITLE
Remove accidentally entered VR2ARs

### ISSUE THREAD

**Issue by xhoenner** [aodn/aatams#301]
Hi Xavier,
 
I have just accidentally created several new VR2ARs in the AATAMS Database which are actually VR2Ws that are already registered. Can you please remove the following VR2ARs when you have the chance please?
 
114543
114535
120741
102026
105863
113118
 
Thanks Mate.
 
Phil.
 
Phil McDowall
IMOS Animal Tracking Facility
Sydney Institute of Marine Science (SIMS)
19 Chowder Bay Road, Mosman, NSW 2088
Ph: + 61 2 9435 4605
M: 0423443737

**Comment by xhoenner** [comment]
@astecken could you please let Phil know that this issue has now been resolved?

**Comment by astecken** [comment]
Done.
