### ISSUE TITLE
Delete manually entered duplicate tag entry

### ISSUE THREAD

**Issue by xhoenner** [aodn/aatams#309]
From @astecken 

Hi Xavier,

Would you be able to delete on of Lachlan's duplicate entries, pls? Thanks! 
________________________________________
From: Lachlan Fetterplace [lcf775@uowmail.edu.au]
Sent: Tuesday, April 12, 2016 12:44 PM
To: Andre Steckenreuter
Cc: Nathan Knott
Subject: Re: Range test tags in IMOS Animal Tracking Database

Hi Andre

I just added all 20 of our sync tags from the Jervis Bay VPS (and two range tags in the VPS).  I stuffed up on one though and duplicated the sensor somehow - A69-1601-65026     serial 1199090. It wont let me fix it...are you able to fix that?

Thanks
Lac

**Comment by xhoenner** [comment]
No worries @astecken, which of the two transmitter type shall I delete though: the pinger or the range test? See https://aatams.emii.org.au/aatams/searchable?q=1199090

**Comment by astecken** [comment]
They should all be range test tags, so delete the pinger, pls :)
