### ISSUE TITLE
Double tag release entries

### ISSUE THREAD

**Issue by xhoenner** [aodn/aatams#312]
From @astecken:

Hi Xavier,

Could you delete the following for Nathan, please? Thanks!

It also appears as though one of the sharks has been listed as having two transmitters. Would it be possible to remove the second tag (i.e. 34797) from this individual? I was unable to do this on my own.

A69-1303-32586
A69-1303-34797
37007001 - Heterodontus portusjacksoni (Port Jackson Shark)	2013-08-03T12:47:48+1000	Orion Beach, Jervis Bay	35.069248°S 150.685238°E (datum:WGS 84)	MQ Port Jackson shark movements and social networks	06/10/2015  

Cheers,
Nathan

On Tue, Apr 12, 2016 at 10:30 AM, Andre Steckenreuter <Andre.Steckenreuter@sims.org.au<mailto:Andre.Steckenreuter@sims.org.au>> wrote:
Hi Nathan,

We came across a tag release that was entered twice. Can one of these entries be deleted?

92990583        A69-1303-32588  MQ Port Jackson shark movements and social networks

Thanks for clarifying!

**Comment by xhoenner** [comment]
What shall I then do for tag id A69-1303-32588 that has been released twice @astecken? I did check and both releases are exactly identical.

**Comment by astecken** [comment]
@xhoenner Pls, delete one entry. Thanks!

**Comment by xhoenner** [comment]
@astecken see below for A69-1303-34797, this tag is still outstanding (it looks like there's an error in the serial number for the 1st record). Would you mind passing that information on to Nathan so that he can advise what he wants us to do?

![screen shot 2016-04-18 at 11 53 36 am](https://cloud.githubusercontent.com/assets/3443821/14591907/473f4ad6-055c-11e6-9004-49a54fa0aa77.jpg)

**Comment by astecken** [comment]
Pls, delete V13 tag model.
