### ISSUE TITLE
Miscellaneous data content errors

### ISSUE THREAD

**Issue by xhoenner** [aodn/aatams#319]
Listed by @astecken.

item | andres_comment | xaviers_comment
---- | -------------- | ---------------
mq project | doesn’t exist | done
Stradbroke workshop project | test project | done
deployment 2015-01-19, 10:02:06, Coral Bay BB6, receiver 114574 | pls delete | done
one of Fiona Small accounts | ask which one; anything entered under this account?: smallf or princess | Not dealt with this
CL1, 101848, 23/08/08, 15:30 | doesn’t exist | done
NL1, , 101764, 22/01/08, 23:30 | double entry | done
A69-1601-12987 | 3 entries, delete 2 of those | Andre to advise which need to be removed
106927 | Charlie GSV units., check if never deployed? | Not dealt with this
101951 | delete receiver and associated deployment | done
all other duplicate sensor entries | contact owners of transmitters that were entered multiple times #208; desktop file 'duplicate sensors'; contacted Xavier to generate new list (see also next rider) | 
Take Kate Lee off Rowley/Scotts projects |  | done
A69-9004-588 pinger | delete | done
my upload for Bondi Line w wrong times | I uploaded the Bondi Line in around 2014? | Not dealt with this
2 OAR installation: OAR (Sydney) and Offshore Artificial Reef | Migrate the OAR installation that has only a single deployment of receiver VR2W-121036 | done
receiver 1068916 | doesn’t exist | done
A69-1601-29724 | delete double enerry with embargo until 30/01/2016 | done
A69-9002-8304 | delete entry with SN 1147846, and pinger entry | done
A69-9002-8305 | delete entry with SN 1147846 (new) | done
A69-9002-84838482 | wrong ID | done
A69-9001-65178, A69-9001-65177, A69-9001-65176, A69-9001-65175, A69-9001-65174,  | change from pinger to range test transmitter type | done
A69-9001-65173 | delete pinger entry | N/A, has already been changed to range test

**Comment by xhoenner** [comment]
Here's below what's left to do for you @astecken before we can close this issue:

item | andres_comment | xaviers_comment
---- | -------------- | ---------------
one of Fiona Small accounts | ask which one; anything entered under this account?: smallf or princess | Not dealt with this
A69-1601-12987 | 3 entries, delete 2 of those | Andre to advise which need to be removed
106927 | Charlie GSV units., check if never deployed? | Not dealt with this
all other duplicate sensor entries | contact owners of transmitters that were entered multiple times #208; desktop file 'duplicate sensors'; contacted Xavier to generate new list (see also next rider) | Not sure what to do with this one.
my upload for Bondi Line w wrong times | I uploaded the Bondi Line in around 2014? | Not dealt with this

**Comment by astecken** [comment]
@xhoenner 
Please, delete Fiona Small's account with username 'princess'

Please, delete these two entries for A69-1601-12987:
A69-1601-12987   37018029 - Negaprion acutidens (Lemon Shark)	2013-12-16T17:35:00+0800	Mangrove Bay	21.9715°S 113.9431°E (datum:WGS 84)	Ningaloo Shark Nursery	16/12/2016
A69-1601-12987   37018029 - Negaprion acutidens (Lemon Shark)	2013-12-16T13:01:00+0800	Mangrove Bay	21.9715°S 113.9431°E (datum:WGS 84)	Ningaloo Shark Nursery	16/12/2016

Please, delete receiver 106927.

After you dealt with these issues, you can close this issue. Thank you!

**Comment by xhoenner** [comment]
Thanks @astecken, closing this issue as now listed [here] (https://github.com/aodn/aatams-content/issues/23)
