### ISSUE TITLE
Delete pinger entries

### ISSUE THREAD

**Issue by xhoenner** [aodn/aatams#326]
From @astecken:

On 27 Apr 2016, at 12:02 PM, Andre Steckenreuter <Andre.Steckenreuter@sims.org.au> wrote:

Hi xavier,

Could you delete the following pinger entries, pls? Thanks heaps!

A69-9001-65177
A69-9001-65178
A69-9001-65179
A69-9001-65180
A69-9001-65181
A69-9001-65182

**Comment by xhoenner** [comment]
@astecken FYI I could only see the first two pingers in the web app.

**Comment by astecken** [comment]
Thanks, even better ;)
