### ISSUE TITLE
Unable to register new tags

### ISSUE THREAD

**Issue by xhoenner** [aodn/aatams#345]
Reported by @astecken and Phil McDowall on 29/07/2016.

<h3> Steps to reproduce <h3>

Go to the [Animal Tracking web app] (https://animaltracking.aodn.org.au). Log in as an admin.
Then go to the [Tag creation page] (https://animaltracking.aodn.org.au/sensor/create). Enter the information indicated in the image below.
![screen shot 2016-08-01 at 1 24 48 pm](https://cloud.githubusercontent.com/assets/3443821/17282643/6271416a-57eb-11e6-8448-750d0fb53e4a.jpg)
Then hit the `Create` button.

<h3> What happens? <h3>

The web app returns the error below.

![screen shot 2016-08-01 at 1 26 11 pm](https://cloud.githubusercontent.com/assets/3443821/17282674/9f9509aa-57eb-11e6-92ef-f4c52a0bd22a.jpg)

<h3> What should happen? <h3>

No error should be returned. As a consequence of this bug it is now impossible for users to register tags via the web app. I therefore suggest to raise this bug as a VIT @smancini and @pblain.

**Comment by lwgordonimos** [comment]
@xhoenner @julian1 We will most likely need to rollback https://github.com/aodn/chef-private/pull/1991/files and https://github.com/aodn/chef/pull/372 unless the source of the "/aatams" URI(s) can be identified...

**Comment by xhoenner** [comment]
that's fine with me @lwgordonimos.

**Comment by julian1** [comment]
Wouldn't a hibernate issue be more likely to be caused by some database inconsistency and the db updates, rather than shuffling around of uris?

**Comment by lwgordonimos** [comment]
@julian1 It seemed very suspicious that the error refers to a "/aatams" URL. Unless it only occurred during the transition.

@xhoenner is this something you are able to replicate yourself currently?

**Comment by julian1** [comment]
@lwgordonimos Can you point me at the /aatams URL?. 

Note that the au.org.emii.aatams stuff in the trace is just the java namespacing used in the app and is expected.

**Comment by julian1** [comment]
Ok, I see it.

**Comment by xhoenner** [comment]
Would you mind trying to register those tags again @astecken and let us know if it's okay now or if you're still experiencing the same issue?

**Comment by astecken** [comment]
Just checked. Issue remains.

**Comment by julian1** [comment]
probably best to wait and we can try to run up a copy to experiment on.

**Comment by jonescc** [comment]
Problem occurs when using the Create Tag (or Sensor) page to add a new sensor to a tag that already exists, changing the device model at the same time.

**Comment by bhasin85** [comment]
Issue fixed. 

![create tag](https://cloud.githubusercontent.com/assets/2552378/17840403/e8797ebc-6849-11e6-8962-ad441f612489.png)

**Comment by xhoenner** [comment]
Can this issue be closed then @bhasin85?

**Comment by bhasin85** [comment]
Sure :)
