### ISSUE TITLE
Impossible to change tag type from pinger to sensor or range test

### ISSUE THREAD

**Issue by xhoenner** [aodn/aatams#347]
## Steps to reproduce

Go to the [Tags page](https://animaltracking.aodn.org.au/sensor/list) and click on the i icon to the left of any tag whose `Transmitter Type` is listed as 'PINGER' (_e.g._ for instance A69-1303-62731). Then click on the `Edit` button.

## What happens

Transmitter type 'PINGER' is not listed anywhere, therefore the only option for users to specify that their tag is actually a sensor tag is to click on the `Add Sensor` button. This will nonetheless create a duplicate as the tag will then be registered as BOTH a pinger and sensor.

## What should happen

`PINGER` should be listed in the table at the bottom of the /tag/show page (similarly to any other sensor or range test type) so that users can click on the i icon on the left and change the tag type without adding a sensor.

**Comment by fjaine** [comment]
List of duplicates created by this issue: https://github.com/aodn/aatams/issues/240#issuecomment-237412539

**Comment by xhoenner** [comment]
While fixing up this issue it would be *very* useful to add additional constraints to the database and/or web app based on the code space restrictions indicated below so that we don't end up with erroneously assigned tag type (see https://github.com/aodn/aatams/issues/240#issuecomment-251265242) in the future.

9002 sensor only
9004 sensor only
1601 pinger only
9001 pinger only

**Comment by fjaine** [comment]
See #240 for latest updates on code spaces:

The below are correct:
1601 - pinger only
9001 - pinger only
9002 - sensor
9004 - sensor
9006 - sensor (new code space to come out in 2017)
1206 - very old code space. Although valid, 1206 was susceptible to false positives so the FDA analysis routine should be applied to any datasets containing these ID to see if they are false positives.

**Comment by bhasin85** [comment]
Fixed by [#361](https://github.com/aodn/aatams/pull/361)
