### ISSUE TITLE
Multiple releases for same tag ID on different animals/species

### ISSUE THREAD

**Issue by xhoenner** [aodn/aatams#352]
@fjaine has recently come across an issue where a researcher released the same tag on two different animals/species at different times (i.e. in 2012 and 2014).

The second tag/animal release is going to be in date conflict with the first one so there needs a new feature in the web app to be able to specify an end date for tag releases, similar to receiver deployments/recoveries. 

Maybe simply with a check box saying "was this transmitter recovered and redeployed?". If checked, then a link to new details for the other release open?

**Comment by fjaine** [comment]
The tag in question is A69-9001-30929 associated with the project 'FRDC WA commercial sharks'. I have added the second release details as a comment to the first release. Ultimately we will need to create another release for this tag with the details below:

Release Date: 13/8/2014
GPS: 21.3919 S, 114.7034 E
Species: Carcharhinus obscurus
Sex: Male
Size: 232 cm TOTAL LENGTH

**Comment by xhoenner** [comment]
This is actually already implemented in the database (and web app) through the `surgery_with_end_date` view which is then joined to the `detection` table based on whether a detection falls within a tag deployment ('surgery_timestamp') start and end dates.
