### ISSUE TITLE
Google analytics script is served for non-production instances

### ISSUE THREAD

**Issue by julian1** [aodn/aatams#370]
eg. view-source:http://aatams-test-instance/aatams/. Tag id is the same as production.

**Comment by lwgordonimos** [comment]
Hardcoded in https://github.com/aodn/aatams/blob/master/grails-app/views/layouts/main.gsp#L111

Not sure the most appropriate way to extract it... Portal derives the per-environment value from config-managed (Chef or EB) Portal.groovy...

**Comment by lwgordonimos** [comment]
Templated based on presence/absence of tracking ID: https://github.com/aodn/aodn-portal/blob/master/grails-app/views/_google_analytics.gsp this could be ported over to here to work similarly?

**Comment by julian1** [comment]
yes, that looks much better.

**Comment by xhoenner** [comment]
Can be closed @lwgordonimos?

**Comment by anguss00** [comment]
Yes, I fixed this one @xhoenner. Closing
