### ISSUE TITLE
Can't edit receiver deployment anymore 

### ISSUE THREAD

**Issue by xhoenner** [aodn/aatams#372]
Go to the [receiver deployment page](https://animaltracking.aodn.org.au/receiverDeployment/list) or try editing a [particular receiver deployment](https://animaltracking.aodn.org.au/receiver/show/58827175). Click on the i icon to the left and you'll get the error below, which probably arose from fixing #241 through https://github.com/aodn/aatams/pull/358 @julian1. 

![screen shot 2017-01-10 at 7 40 02 am](https://cloud.githubusercontent.com/assets/3443821/21782596/0bfa34c6-d708-11e6-8b86-77affac14d60.jpg)

@pblain this should be a VIT: if we're not fixing up this bug then nobody will be able to edit their receiver deployment metadata.

**Comment by fjaine** [comment]
Yep @xhoenner we noted the same error this morning when checking on some receiver details for our fieldwork tomorrow. It's pretty urgent.

**Comment by julian1** [comment]
https://github.com/aodn/aatams/compare/fix_372?expand=1

**Comment by julian1** [comment]
https://github.com/aodn/aatams/pull/379

**Comment by julian1** [comment]
https://github.com/aodn/aatams/pull/380
