### ISSUE TITLE
aatams compile and startup is very slow

### ISSUE THREAD

**Issue by julian1** [aodn/aatams#378]
With *no* code modifications, and after hitting the intellij debug button, it takes over a minute before the webapp answers in the browser - on my quad i7. 

Session cookies are not persisted, so further time is needed to perform login - if admin specific functionality is being developed.

In comparison - Geoserver (not geoserver_build), a project with probably 100x the codebase size takes around 20 seconds.

**Comment by jonescc** [comment]
Works fine for me after applying required dependency changes in https://github.com/aodn/aatams/pull/394.

I will note however that the intellij grails plugin only supports grails 2.0.0 onwards but this doesn't appear to affect compilation/debugging which uses the grails 1.3.7 compiler.
