### ISSUE TITLE
Error encountered uploading data on 29/10

### ISSUE THREAD

**Issue by kereid** [aodn/aatams#42]
This issue is probably related to #29 but seen by a different person loading up different things? so am logging it so it's on record as being reported, and then I can follow up with James and maybe Stephanie when issue #29 is resolved. 

Email from James for the record:

Thanks for the email regarding the database issues we are facing. I just would like to clarify that it is not only the project manta csv uploads that are recording error messages. I have also received errors from shoalhaven uploads and I believe Stephanie Brodie also encountered an error whilst uploading data on the 29/10. I am unsure if these errors are related to the same issue or not.

**Comment by jkburges** [comment]
Closing this.  Trying to upload the "project manta" file results in an error: "Incorrect format for Date/Time expected yyyy-MM-dd HH:mm:ss Z" which is correct given the date format used in the file (e.g. 13/09/2007 12:38)
