### ISSUE TITLE
QC.R stops with 'Error in validityMethod(object) : invalid extent: ymin >= ymaxi'

### ISSUE THREAD

**Issue by jganong** [aodn/aatams#421]
`setwd('aatams/scripts/R/QC'); source('QC.R') `

results in:

`Error in validityMethod(object) : invalid extent: ymin >= ymaxi`

This comes from line 17 in `QC.R`, which reads:

`Aust <- crop(getMap(resolution="high"), extent(110,155,-5,-45));`

but -5 is greater than -45, so they need to be swapped, 
it runs fine if you do it like this:

`Aust <- crop(getMap(resolution="high"), extent(110,155,-45,-5));`

**Comment by xhoenner** [comment]
The `raster` package must have changed the definition of the extent function, thanks for pointing that out @jganong and putting up this PR!
