### ISSUE TITLE
Possible to upload duplicates of tag deployments without recoveries

### ISSUE THREAD

**Issue by RossDwyer** [aodn/aatams#463]
While uploading Tag Releases for the project Grey Nurse Shark_Diver Interactions, I encountered an issue where typing in the metadata for the release of a shark with ID tag code 6395 would not upload into the database. On closer inspection, adding this tag release resulted in the duplicate release of tag ID 6381 (but with a new deployment dte, shark length/sex etc) as these ids incorrectly had the same serial numbers upon data entry. I have updated the tag data in https://animaltracking.aodn.org.au/sensor/list so that tags now have the correct serial numbers, however these duplicate releases still exist in https://animaltracking.aodn.org.au/animalRelease/list.

I have highlighted the incorrect releases of ID 6381 in the Comments section for this tag release  as "DELETE. This entry needs to be deleted".

**Comment by evacougnon** [comment]
@RossDwyer I copied this issue to the content repo to track DB content issues, I'll be in touch soon
