### ISSUE TITLE
Incorrectly accessible detections when logged out

### ISSUE THREAD

**Issue by kereid** [aodn/aatams#55]
Reported by Andrew Boomer on behalf of Malcolm Francis (NIWA)

This will need investigation into when AB detections were uploaded to see if they were before the bug was fixed that was not associating detections and tags if they were entered in the "wrong" order. Could be a left over from that and require a big tidy up, or it may be a re-introduced bug.

Steps to reproduce:

From notification email user would click data link (as per trail) and be taken to https://aatams.emii.org.au/aatams/detection/list?filter.in=transmitterId&filter.in=A69-1303-40969 making sure user is logged out click export data as csv and open.

The log in and again click export data as csv

Compare the 2 files.

What should happen:

When logged out user should get no results downloaded

When logged in user should get all 257 records from that tag number with all details filled in

What does happen:

When logged out get 181 results that do not have species associated so system doesn't know to keep them secure

When logged in user does get all 257 records but AB uploads are missing details 

Email trail:

No there is no embargo on receiver data,

My best guess is it’s a bug in the system but I will confirm this soon,

Thanks for the feedback,

Andrew

From: Malcolm Francis [mailto:Malcolm.Francis@niwa.co.nz] 
Sent: Tuesday, 26 November 2013 3:09 AM
To: Andrew Boomer
Subject: RE: AATAMS detections for tags [A69-1303-40969, A69-1601-3301]

OK, this is weird. I just compared the two downloads (logged in and not logged in) and when I’m not logged in I can retrieve all 181 records uploaded by someone called Andrew Boomer, but none of the records uploaded by Phil McDowall (15) or Stephanie Brodie (61). So is there an embargo or block on those data if not logged in? Or is it a data format issue – I just checked and found that  none of your uploaded records have  entries in the ‘tag ID’ and ‘species’ columns, whereas all the uploads by the other two do. 
 
Cheers
 
Malcolm
 
Malcolm Francis
Principal Scientist, Coastal Group
National Institute of Water and Atmospheric Research Ltd
301 Evans Bay Parade, Greta Point, Wellington 6021, New Zealand
Private Bag 14901, Wellington 6241, New Zealand
Phone +64 4 386 0377
 
From: Andrew Boomer [mailto:Andrew.Boomer@sims.org.au] 
Sent: Tuesday, 26 November 2013 3:59 p.m.
To: Malcolm Francis
Subject: RE: AATAMS detections for tags [A69-1303-40969, A69-1601-3301]
 
Thanks Malcolm,
 
The record should be the same just the information is somewhat restricted for the logged out version,
 
Make sure that you are logged in as the information is of higher resolution in this view,
 
I will send this on to the eMII guys,
 
Regards,
 
Andrew
 
From: Malcolm Francis [mailto:Malcolm.Francis@niwa.co.nz] 
Sent: Tuesday, 26 November 2013 2:56 AM
To: Andrew Boomer
Subject: RE: AATAMS detections for tags [A69-1303-40969, A69-1601-3301]
 
Yep, that’s the problem. I get 257 records when logged in and 181 recorded when not for tag A69-1303-40969.
 
Cheers
 
Malcolm
 
Malcolm Francis
Principal Scientist, Coastal Group
National Institute of Water and Atmospheric Research Ltd
301 Evans Bay Parade, Greta Point, Wellington 6021, New Zealand
Private Bag 14901, Wellington 6241, New Zealand
Phone +64 4 386 0377
 
From: Andrew Boomer [mailto:Andrew.Boomer@sims.org.au] 
Sent: Tuesday, 26 November 2013 3:51 p.m.
To: Malcolm Francis
Subject: RE: AATAMS detections for tags [A69-1303-40969, A69-1601-3301]
 
Ok I can’t seem to replicate this one at all,
 
I will forward this on to the tech guys and see if we have a bug in the system,
 
Out of curiosity can you log in and see if you get the same problem,
 
Andrew
 
From: Malcolm Francis [mailto:Malcolm.Francis@niwa.co.nz] 
Sent: Saturday, 23 November 2013 3:11 AM
To: Andrew Boomer
Subject: FW: AATAMS detections for tags [A69-1303-40969, A69-1601-3301]
 
Re my data retrieval issue, please try the following and see what you get (this is what I've been doing):
 
1. Click on the 'data' link next to tag 40969. This should bring up the tag detections page listing "257 matching records" and showing the first of 13 pages of data.
2. Click on "export data as csv" box. Then "Open".
 
This delivers 181 records to me. How many do you get?
 
Note: I am not logged in while doing this - would that make a difference?
 
Cheers
 
Malcolm
 
Malcolm Francis
Principal Scientist, Coastal Group
National Institute of Water and Atmospheric Research Ltd
301 Evans Bay Parade, Greta Point, Wellington 6021, New Zealand
Private Bag 14901, Wellington 6241, New Zealand
Phone +64 4 386 0377, Fax +64 4 386 0574
________________________________________
From: aatams_system@emii.org.au [aatams_system@emii.org.au]
Sent: Tuesday, 12 November 2013 12:25 p.m.
To: Malcolm Francis
Subject: AATAMS detections for tags [A69-1303-40969, A69-1601-3301]
Dear Malcolm Francis,

The following tags have new detections as a result of a recent upload:
Tag	Link to the data
A69-1303-40969
data...

A69-1601-3301
data...

Regards,
The AATAMS team

**Comment by ktattersall** [comment]
@jkburges @kereid Do you know if this issue has been resolved by the materialised view work? If so, can we close it?

**Comment by jkburges** [comment]
Probably - but it's worth verifying I think.

**Comment by kereid** [comment]
@jkburges is that verification from our end or Andre?

**Comment by jkburges** [comment]
Either really.

**Comment by kereid** [comment]
As the embargo date has passed for the original tag the we cannot attempt to reproduce the issue to validate the fix, it is not easy to find embargoed tags that have detections in the database - therefore we will require developer assistance to be able to confirm if this has been resolved.

**Comment by xhoenner** [comment]
Just tried re-creating that issue using tag_id = 'A69-1105-2' which is currently embargoed. When logged out and logged in I downloaded the same number of rows (14) but with no species information for the former, which is the expected behaviour. Same thing happened when downloading detections for another currently embargoed tag 'A69-1303-3773'.

I believe this can be closed @jkburges .

**Comment by jkburges** [comment]
![image](https://cloud.githubusercontent.com/assets/1849176/10036702/45b24a68-61ee-11e5-850f-359ea60af9e6.png)
