### ISSUE TITLE
Missing Tag detections from Receiver

### ISSUE THREAD

**Issue by kereid** [aodn/aatams#56]
Hi Kate,
 
I have just been entering tags for the project VIC Fisheries Snapper- Port Phillip Bay. I have entered 140 tags and have completed tag releases for all of them. 
 
When I search for tag detections under this project it comes up with 230 detections all received on the station 01 Gellibrand. The receiver ID for the 01 Gelibrand station is 107481. When I look at the Vemco Database file that was used to export the CSV uploaded to the AATAMS database it shows a total of 1353 detections for receiver 107481. 
 
The total number of detections for all receivers in this Vemco database is 520070. This suggests that we should expect to see far more detections associated with the Vic Fisheries Snapper- Port Phillip Bay Project in the AATAMS database.
 
Can you please take a look at this issue for me and see if you can see where the error is occurring?
 
Kind Regards

Phil McDowall 

Hi Phil,
 
Can you please send through the csv file from VEMCO (if possible) so we can have a look at it and also roughly when did you do your upload? 
 
Cheers,
Kate

Hi Kate, 
 
Thanks for getting back to me, I have attached the csv files that were uploaded to the database. The files were uploaded to the AATAMS database on 11/12/2012 under the name Kade Mills Snapper Port Philip Bay 2012 events.csv  & Kade Mills Snapper Port Philip Bay 2012 detections.csv  . The uploader was Andre Steckenreuter.
 
Hope it helps.
 
Kind Regards

Phil McDowall 

Note from Kate as Github won't allow files to be uploaded csv is saved in

Shery; > HelpDesk > AATAMS > Port Philip Bay Kade Mills CSV files uploaded to DAtabase

**Comment by jkburges** [comment]
Ref: https://aatams-systest.aodn.org.au/aatams/receiverDownloadFile/show/38993069

**Comment by jkburges** [comment]
List of "unknown receivers" in the export:

<pre>VR2-4715, VR2W-114832, VR2W-107487, VR2W-107515, VR2W-107508, VR2-6412, VR2-7302, VR2W-114827, VR2W-114823, VR2W-114829, VR2-4780, VR2W-107512, VR2-6441, VR2W-107504, VR2W-108126, VR2W-108128, VR2-7297, VR2W-107489, VR2W-107478, VR2W-114833, VR2-4713, VR2W-107488, VR2W-107485, VR2-7314, VR2-6434, VR2-7313, VR2W-107509, VR2-4711, VR2W-114828, VR2-7311, VR2-7298, VR2W-107483, VR2W-107498, VR2W-114824, VR2-6410, VR2W-107495, VR2W-107480, VR2W-107476, VR2-7305, VR2-7309, VR2W-114825, VR2-6419, VR2-6416, VR2W-107477, VR2-7296, VR2-4716, VR2W-107479, VR2-7295, VR2W-107486, VR2W-107493, VR2W-114826, VR2W-107482
</pre>

**Comment by jkburges** [comment]
Receivers known to DB:
<pre>"VR2W-108126"
"VR2W-107479"
"VR2W-107478"
"VR2W-114832"
"VR2W-107487"
"VR2W-107509"
"VR2W-107515"
"VR2W-107493"
"VR2W-114827"
"VR2W-107508"
"VR2W-114828"
"VR2W-107486"
"VR2W-107489"
"VR2W-114833"
"VR2W-107477"
"VR2W-107498"
"VR2W-107488"
"VR2W-114823"
"VR2W-107480"
"VR2W-114824"
"VR2W-107512"
"VR2W-108128"
</pre>

**Comment by jkburges** [comment]
Based on the above, I'd say that the low number of detections is due to two different things:

1. receivers not known the DB, i.e. those with a blank "known" column in https://github.com/aodn/aatams/issues/56#issuecomment-73185178
2. receiver meta data being entered *after* the detection file was uploaded

**Comment by ktattersall** [comment]
@kereid have you had an opportunity to contact Andre about this? If not, would you like me to follow up?

**Comment by kereid** [comment]
Oh no must have missed that one, I'll ask him to have a look into it.

**Comment by astecken** [comment]
I have entered all unknown receivers that were listed above. All VR2 receivers were entered originally as VR2-xxxxC but I changed them all to the VR2-xxxx format. I think the correct format does incl. the 'C' but I am not sure why the detections are not linked to it accordingly. 

@kereid: Would you be able to upload teh csv file again so we can see if we made any progress? Thanks!

**Comment by jkburges** [comment]
The 'C' on the end *should* be fine (so long as this matches what's in the detection CSV file).

**Comment by kereid** [comment]
Emailed @astecken the csv file to re-upload and see if anything has changed

**Comment by astecken** [comment]
I uploaded both files (events and detections) again. This is a copy of the report:

Type	detections (CSV)
Path	/mnt/ebs/aatams/fileimports/125433205/Kade Mills Snapper Port Phillip Bay 2012 detections.csv
Err Msg	
Import Date	07/05/2015 14:43:59
Name	Kade Mills Snapper Port Phillip Bay 2012 detections.csv
Uploader	Andre Steckenreuter
Status	PROCESSED
Total Detections	511823
Valid Count	497840
Invalid Count	13983
Duplicate Count	230
Unknown Receiver Count	0
Unknown Receivers	[]
No Deployment at Time Count	13748
No Recovery at Time Count	5

The 'unknown receiver count' issue seems to be resolved. However, There's still a large number of 'no deployment at time count' that I'll try to resolve from this end by reviewing the data. I'll keep you posted.

**Comment by xhoenner** [comment]
@jkburges given https://github.com/aodn/backlog/issues/100 was closed, can this issue be closed too?

**Comment by jkburges** [comment]
I'd say so.
