### ISSUE TITLE
Wrong values in num_deployment in installation_station table 

### ISSUE THREAD

**Issue by xhoenner** [aodn/aatams#70]
Steps To Repeat:
Connected to aatams3, wanted to list the name of all installation stations, along with their corresponding number of deployments and number of detections. Ran the following SQL to do this:

SELECT installation_station.name AS station_name,
   installation_station.num_deployments AS no_deployments,
   COUNT(*) AS no_detections
   FROM aatams.valid_detection
   FULL JOIN aatams.receiver_deployment ON valid_detection.receiver_deployment_id = receiver_deployment.id
   FULL JOIN aatams.installation_station ON receiver_deployment.station_id = installation_station.id
   GROUP BY installation_station.name,installation_station.num_deployments
   ORDER BY no_deployments;

What I Expected To Happen:
I expected to get a list in which the number of deployments could not be equal to zero if there were detections. The values in the 'num_deployments' column of the installation_station table are therefore erroneous.

What Actually Happened:
A lot of installation stations had many detections and yet the number of deployments was equal to zero. Additionally, many installation stations had a number of detections equal to 1, not sure whether it's an error in the database too.

**Comment by xhoenner** [comment]
@jkburges that field doesn't exist anymore in the `installation_station` table, happy to close it?

**Comment by jkburges** [comment]
Yes - this value is now derived (as it should be) - see: https://github.com/aodn/aatams/blob/master/grails-app/domain/au/org/emii/aatams/InstallationStation.groovy#L94
