### ISSUE TITLE
Stations not visible under a project even with Read/Write access

### ISSUE THREAD

**Issue by kereid** [aodn/aatams#80]
Reported by James van den Broek:

Stations belong to projects.
People must be added to projects to see station names.

James was a member of the UQ Manta Ray project.

In "Create receiver deployment" James clicked the station drop down or started typing to auto complete.

Stations belonging to the project such as LEI_LHB, LEI_Groupler did not appear

Removed James as a member of project, added him back on.

He could now see the station names.

**Comment by ktattersall** [comment]
@dnahodil just checking if this has been resolved by work on #196? Can we close this issue?

**Comment by dnahodil** [comment]
If I recall, @jkburges thought something else might be going on in this issue so the resolution for #196 probably wouldn't be enough. We'll have to see if we can reproduce this issue to see if the other work has changed anything.

**Comment by xhoenner** [comment]
Trying to recreate that issue, but for that I need to add myself to a project and remove myself afterwards through manual deletion in the database which is not very safe. @jkburges might be worth looking at that when resuscitating systest instead.

**Comment by xhoenner** [comment]
@astecken is a member of that project and wasn't able to recreate this issue.
